// Class EditableMesh.EditableMeshAdapter
// Size: 0x28 (Inherited: 0x28)
struct UEditableMeshAdapter : UObject {
};

// Class EditableMesh.EditableGeometryCollectionAdapter
// Size: 0xd8 (Inherited: 0x28)
struct UEditableGeometryCollectionAdapter : UEditableMeshAdapter {
	struct UGeometryCollection* GeometryCollection; // 0x28(0x08)
	struct UGeometryCollection* OriginalGeometryCollection; // 0x30(0x08)
	int32_t GeometryCollectionLODIndex; // 0x38(0x04)
	char pad_3C[0x9c]; // 0x3c(0x9c)
};

// Class EditableMesh.EditableMesh
// Size: 0x708 (Inherited: 0x28)
struct UEditableMesh : UObject {
	char pad_28[0x390]; // 0x28(0x390)
	struct TArray<struct UEditableMeshAdapter*> Adapters; // 0x3b8(0x10)
	char pad_3C8[0x8]; // 0x3c8(0x08)
	int32_t TextureCoordinateCount; // 0x3d0(0x04)
	char pad_3D4[0x148]; // 0x3d4(0x148)
	int32_t PendingCompactCounter; // 0x51c(0x04)
	int32_t SubdivisionCount; // 0x520(0x04)
	char pad_524[0x1e4]; // 0x524(0x1e4)

	void WeldVertices(struct TArray<struct FVertexID>& VertexIDs, struct FVertexID& OutNewVertexID); // Function EditableMesh.EditableMesh.WeldVertices // (NetRequest|NetResponse|UbergraphFunction|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145cc40
	void TryToRemoveVertex(struct FVertexID VertexID, bool& bOutWasVertexRemoved, struct FEdgeID& OutNewEdgeID); // Function EditableMesh.EditableMesh.TryToRemoveVertex // (NetResponse|UbergraphFunction|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	void TryToRemovePolygonEdge(struct FEdgeID EdgeID, bool& bOutWasEdgeRemoved, struct FPolygonID& OutNewPolygonID); // Function EditableMesh.EditableMesh.TryToRemovePolygonEdge // (Net|NetReliableExec|Native|Event|UbergraphFunction|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	void TriangulatePolygons(struct TArray<struct FPolygonID>& PolygonIDs, struct TArray<struct FPolygonID>& OutNewTrianglePolygons); // Function EditableMesh.EditableMesh.TriangulatePolygons // (NetReliableNetRequest|Native|Event|UbergraphFunction|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	void TessellatePolygons(struct TArray<struct FPolygonID>& PolygonIDs, enum class ETriangleTessellationMode TriangleTessellationMode, struct TArray<struct FPolygonID>& OutNewPolygonIDs); // Function EditableMesh.EditableMesh.TessellatePolygons // (Net|Native|Event|UbergraphFunction|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	void StartModification(enum class EMeshModificationType MeshModificationType, enum class EMeshTopologyChange MeshTopologyChange); // Function EditableMesh.EditableMesh.StartModification // (NetReliableNetRequest|Exec|Event|UbergraphFunction|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	void SplitPolygons(struct TArray<struct FPolygonToSplit>& PolygonsToSplit, struct TArray<struct FEdgeID>& OutNewEdgeIDs); // Function EditableMesh.EditableMesh.SplitPolygons // (Net|Exec|Event|UbergraphFunction|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	void SplitPolygonalMesh(struct FPlane& InPlane, struct TArray<struct FPolygonID>& PolygonIDs1, struct TArray<struct FPolygonID>& PolygonIDs2, struct TArray<struct FEdgeID>& BoundaryIDs); // Function EditableMesh.EditableMesh.SplitPolygonalMesh // (NetReliableEvent|UbergraphFunction|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	void SplitEdge(struct FEdgeID EdgeID, struct TArray<float>& Splits, struct TArray<struct FVertexID>& OutNewVertexIDs); // Function EditableMesh.EditableMesh.SplitEdge // (NetRequest|Exec|Native|UbergraphFunction|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	void SetVerticesCornerSharpness(struct TArray<struct FVertexID>& VertexIDs, struct TArray<float>& VerticesNewCornerSharpness); // Function EditableMesh.EditableMesh.SetVerticesCornerSharpness // (Exec|Native|UbergraphFunction|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	void SetVerticesAttributes(struct TArray<struct FAttributesForVertex>& AttributesForVertices); // Function EditableMesh.EditableMesh.SetVerticesAttributes // (NetRequest|Native|UbergraphFunction|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	void SetVertexInstancesAttributes(struct TArray<struct FAttributesForVertexInstance>& AttributesForVertexInstances); // Function EditableMesh.EditableMesh.SetVertexInstancesAttributes // (Net|Native|UbergraphFunction|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	void SetTextureCoordinateCount(int32_t NumTexCoords); // Function EditableMesh.EditableMesh.SetTextureCoordinateCount // (Net|NetReliableNetRequest|Exec|UbergraphFunction|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	void SetSubdivisionCount(int32_t NewSubdivisionCount); // Function EditableMesh.EditableMesh.SetSubdivisionCount // (Net|NetRequest|Exec|UbergraphFunction|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	void SetPolygonsVertexAttributes(struct TArray<struct FVertexAttributesForPolygon>& VertexAttributesForPolygons); // Function EditableMesh.EditableMesh.SetPolygonsVertexAttributes // (Net|NetReliableNetRequest|UbergraphFunction|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	void SetEdgesHardnessAutomatically(struct TArray<struct FEdgeID>& EdgeIDs, float MaxDotProductForSoftEdge); // Function EditableMesh.EditableMesh.SetEdgesHardnessAutomatically // (Net|NetReliableUbergraphFunction|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	void SetEdgesHardness(struct TArray<struct FEdgeID>& EdgeIDs, struct TArray<bool>& EdgesNewIsHard); // Function EditableMesh.EditableMesh.SetEdgesHardness // (Net|NetReliableNetRequest|Exec|Native|Event|NetResponse|Static|NetMulticast|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	void SetEdgesCreaseSharpness(struct TArray<struct FEdgeID>& EdgeIDs, struct TArray<float>& EdgesNewCreaseSharpness); // Function EditableMesh.EditableMesh.SetEdgesCreaseSharpness // (NetReliableExec|Native|Event|NetResponse|Static|NetMulticast|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	void SetEdgesAttributes(struct TArray<struct FAttributesForEdge>& AttributesForEdges); // Function EditableMesh.EditableMesh.SetEdgesAttributes // (Net|NetReliableNetRequest|Native|Event|NetResponse|Static|NetMulticast|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	void SetAllowUndo(bool bInAllowUndo); // Function EditableMesh.EditableMesh.SetAllowUndo // (Net|NetRequest|Native|Event|NetResponse|Static|NetMulticast|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	void SetAllowSpatialDatabase(bool bInAllowSpatialDatabase); // Function EditableMesh.EditableMesh.SetAllowSpatialDatabase // (Net|NetReliableNative|Event|NetResponse|Static|NetMulticast|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	void SetAllowCompact(bool bInAllowCompact); // Function EditableMesh.EditableMesh.SetAllowCompact // (Net|Native|Event|NetResponse|Static|NetMulticast|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	void SearchSpatialDatabaseForPolygonsPotentiallyIntersectingPlane(struct FPlane& InPlane, struct TArray<struct FPolygonID>& OutPolygons); // Function EditableMesh.EditableMesh.SearchSpatialDatabaseForPolygonsPotentiallyIntersectingPlane // (Net|NetRequest|Exec|Event|NetResponse|Static|NetMulticast|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	void SearchSpatialDatabaseForPolygonsPotentiallyIntersectingLineSegment(struct FVector LineSegmentStart, struct FVector LineSegmentEnd, struct TArray<struct FPolygonID>& OutPolygons); // Function EditableMesh.EditableMesh.SearchSpatialDatabaseForPolygonsPotentiallyIntersectingLineSegment // (Net|NetReliableNetRequest|Event|NetResponse|Static|NetMulticast|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	void SearchSpatialDatabaseForPolygonsInVolume(struct TArray<struct FPlane>& Planes, struct TArray<struct FPolygonID>& OutPolygons); // Function EditableMesh.EditableMesh.SearchSpatialDatabaseForPolygonsInVolume // (Net|NetReliableEvent|NetResponse|Static|NetMulticast|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	struct UEditableMesh* RevertInstance(); // Function EditableMesh.EditableMesh.RevertInstance // (NetReliableEvent|NetResponse|Static|NetMulticast|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	void Revert(); // Function EditableMesh.EditableMesh.Revert // (NetReliableNetRequest|Exec|Native|NetResponse|Static|NetMulticast|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	void RebuildRenderMesh(); // Function EditableMesh.EditableMesh.RebuildRenderMesh // (NetReliableEvent|NetResponse|Static|NetMulticast|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	void QuadrangulateMesh(struct TArray<struct FPolygonID>& OutNewPolygonIDs); // Function EditableMesh.EditableMesh.QuadrangulateMesh // (Net|NetReliableNetRequest|Exec|Native|NetResponse|Static|NetMulticast|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	void PropagateInstanceChanges(); // Function EditableMesh.EditableMesh.PropagateInstanceChanges // (NetReliableNetRequest|Exec|Native|NetResponse|Static|NetMulticast|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	void MoveVertices(struct TArray<struct FVertexToMove>& VerticesToMove); // Function EditableMesh.EditableMesh.MoveVertices // (NetRequest|Exec|Native|NetResponse|Static|NetMulticast|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	struct FVertexID MakeVertexID(int32_t VertexIndex); // Function EditableMesh.EditableMesh.MakeVertexID // (NetReliableExec|Native|NetResponse|Static|NetMulticast|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	struct FPolygonID MakePolygonID(int32_t PolygonIndex); // Function EditableMesh.EditableMesh.MakePolygonID // (NetReliableExec|Native|NetResponse|Static|NetMulticast|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	struct FPolygonGroupID MakePolygonGroupID(int32_t PolygonGroupIndex); // Function EditableMesh.EditableMesh.MakePolygonGroupID // (NetReliableExec|Native|NetResponse|Static|NetMulticast|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	struct FEdgeID MakeEdgeID(int32_t EdgeIndex); // Function EditableMesh.EditableMesh.MakeEdgeID // (NetReliableExec|Native|NetResponse|Static|NetMulticast|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	bool IsValidVertex(struct FVertexID VertexID); // Function EditableMesh.EditableMesh.IsValidVertex // (Net|NetReliableNetRequest|Native|NetResponse|Static|NetMulticast|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	bool IsValidPolygonGroup(struct FPolygonGroupID PolygonGroupID); // Function EditableMesh.EditableMesh.IsValidPolygonGroup // (Net|NetRequest|Native|NetResponse|Static|NetMulticast|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	bool IsValidPolygon(struct FPolygonID PolygonID); // Function EditableMesh.EditableMesh.IsValidPolygon // (Net|NetReliableNative|NetResponse|Static|NetMulticast|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	bool IsValidEdge(struct FEdgeID EdgeID); // Function EditableMesh.EditableMesh.IsValidEdge // (Net|Native|NetResponse|Static|NetMulticast|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	bool IsUndoAllowed(); // Function EditableMesh.EditableMesh.IsUndoAllowed // (Native|NetResponse|Static|NetMulticast|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	bool IsSpatialDatabaseAllowed(); // Function EditableMesh.EditableMesh.IsSpatialDatabaseAllowed // (Native|NetResponse|Static|NetMulticast|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	bool IsPreviewingSubdivisions(); // Function EditableMesh.EditableMesh.IsPreviewingSubdivisions // (Net|NetReliableNetRequest|Exec|NetResponse|Static|NetMulticast|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	bool IsOrphanedVertex(struct FVertexID VertexID); // Function EditableMesh.EditableMesh.IsOrphanedVertex // (Net|NetRequest|Exec|NetResponse|Static|NetMulticast|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	bool IsCompactAllowed(); // Function EditableMesh.EditableMesh.IsCompactAllowed // (NetRequest|Exec|NetResponse|Static|NetMulticast|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	bool IsCommittedAsInstance(); // Function EditableMesh.EditableMesh.IsCommittedAsInstance // (Net|NetReliableExec|NetResponse|Static|NetMulticast|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	bool IsCommitted(); // Function EditableMesh.EditableMesh.IsCommitted // (Net|NetReliableExec|NetResponse|Static|NetMulticast|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	bool IsBeingModified(); // Function EditableMesh.EditableMesh.IsBeingModified // (NetReliableExec|NetResponse|Static|NetMulticast|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	struct FVertexID InvalidVertexID(); // Function EditableMesh.EditableMesh.InvalidVertexID // (Net|Exec|NetResponse|Static|NetMulticast|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	struct FPolygonID InvalidPolygonID(); // Function EditableMesh.EditableMesh.InvalidPolygonID // (Net|Exec|NetResponse|Static|NetMulticast|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	struct FPolygonGroupID InvalidPolygonGroupID(); // Function EditableMesh.EditableMesh.InvalidPolygonGroupID // (Exec|NetResponse|Static|NetMulticast|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	struct FEdgeID InvalidEdgeID(); // Function EditableMesh.EditableMesh.InvalidEdgeID // (Exec|NetResponse|Static|NetMulticast|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	void InsetPolygons(struct TArray<struct FPolygonID>& PolygonIDs, float InsetFixedDistance, float InsetProgressTowardCenter, enum class EInsetPolygonsMode Mode, struct TArray<struct FPolygonID>& OutNewCenterPolygonIDs, struct TArray<struct FPolygonID>& OutNewSidePolygonIDs); // Function EditableMesh.EditableMesh.InsetPolygons // (Net|NetReliableNetRequest|Exec|Native|Event|Static|NetMulticast|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	void InsertEdgeLoop(struct FEdgeID EdgeID, struct TArray<float>& Splits, struct TArray<struct FEdgeID>& OutNewEdgeIDs); // Function EditableMesh.EditableMesh.InsertEdgeLoop // (NetReliableExec|Native|Event|Static|NetMulticast|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	void InitializeAdapters(); // Function EditableMesh.EditableMesh.InitializeAdapters // (Net|Exec|Native|Event|Static|NetMulticast|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	struct FEdgeID GetVertexPairEdge(struct FVertexID VertexID, struct FVertexID NextVertexID, bool& bOutEdgeWindingIsReversed); // Function EditableMesh.EditableMesh.GetVertexPairEdge // (NetRequest|Native|Event|Static|NetMulticast|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	struct FVertexID GetVertexInstanceVertex(struct FVertexInstanceID VertexInstanceID); // Function EditableMesh.EditableMesh.GetVertexInstanceVertex // (NetReliableNative|Event|Static|NetMulticast|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	int32_t GetVertexInstanceCount(); // Function EditableMesh.EditableMesh.GetVertexInstanceCount // (Net|Native|Event|Static|NetMulticast|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	void GetVertexInstanceConnectedPolygons(struct FVertexInstanceID VertexInstanceID, struct TArray<struct FPolygonID>& OutConnectedPolygonIDs); // Function EditableMesh.EditableMesh.GetVertexInstanceConnectedPolygons // (Net|NetRequest|Exec|Event|Static|NetMulticast|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	int32_t GetVertexInstanceConnectedPolygonCount(struct FVertexInstanceID VertexInstanceID); // Function EditableMesh.EditableMesh.GetVertexInstanceConnectedPolygonCount // (Net|NetReliableExec|Event|Static|NetMulticast|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	struct FPolygonID GetVertexInstanceConnectedPolygon(struct FVertexInstanceID VertexInstanceID, int32_t ConnectedPolygonNumber); // Function EditableMesh.EditableMesh.GetVertexInstanceConnectedPolygon // (Exec|Event|Static|NetMulticast|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	int32_t GetVertexCount(); // Function EditableMesh.EditableMesh.GetVertexCount // (Net|NetReliableNetRequest|Event|Static|NetMulticast|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	void GetVertexConnectedPolygons(struct FVertexID VertexID, struct TArray<struct FPolygonID>& OutConnectedPolygonIDs); // Function EditableMesh.EditableMesh.GetVertexConnectedPolygons // (Net|NetReliableEvent|Static|NetMulticast|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	void GetVertexConnectedEdges(struct FVertexID VertexID, struct TArray<struct FEdgeID>& OutConnectedEdgeIDs); // Function EditableMesh.EditableMesh.GetVertexConnectedEdges // (Event|Static|NetMulticast|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	int32_t GetVertexConnectedEdgeCount(struct FVertexID VertexID); // Function EditableMesh.EditableMesh.GetVertexConnectedEdgeCount // (Net|NetRequest|Exec|Native|Static|NetMulticast|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	struct FEdgeID GetVertexConnectedEdge(struct FVertexID VertexID, int32_t ConnectedEdgeNumber); // Function EditableMesh.EditableMesh.GetVertexConnectedEdge // (NetReliableExec|Native|Static|NetMulticast|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	void GetVertexAdjacentVertices(struct FVertexID VertexID, struct TArray<struct FVertexID>& OutAdjacentVertexIDs); // Function EditableMesh.EditableMesh.GetVertexAdjacentVertices // (NetReliableNetRequest|Native|Static|NetMulticast|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	int32_t GetTextureCoordinateCount(); // Function EditableMesh.EditableMesh.GetTextureCoordinateCount // (NetReliableNetRequest|Native|Static|NetMulticast|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	struct FSubdivisionLimitData GetSubdivisionLimitData(); // Function EditableMesh.EditableMesh.GetSubdivisionLimitData // (Net|NetRequest|Native|Static|NetMulticast|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	int32_t GetSubdivisionCount(); // Function EditableMesh.EditableMesh.GetSubdivisionCount // (NetRequest|Native|Static|NetMulticast|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	int32_t GetPolygonTriangulatedTriangleCount(struct FPolygonID PolygonID); // Function EditableMesh.EditableMesh.GetPolygonTriangulatedTriangleCount // (NetReliableNative|Static|NetMulticast|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	struct FTriangleID GetPolygonTriangulatedTriangle(struct FPolygonID PolygonID, int32_t PolygonTriangleNumber); // Function EditableMesh.EditableMesh.GetPolygonTriangulatedTriangle // (NetReliableNetRequest|Exec|Static|NetMulticast|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	void GetPolygonPerimeterVertices(struct FPolygonID PolygonID, struct TArray<struct FVertexID>& OutPolygonPerimeterVertexIDs); // Function EditableMesh.EditableMesh.GetPolygonPerimeterVertices // (Net|NetReliableExec|Static|NetMulticast|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	void GetPolygonPerimeterVertexInstances(struct FPolygonID PolygonID, struct TArray<struct FVertexInstanceID>& OutPolygonPerimeterVertexInstanceIDs); // Function EditableMesh.EditableMesh.GetPolygonPerimeterVertexInstances // (Net|NetReliableNetRequest|Static|NetMulticast|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	struct FVertexInstanceID GetPolygonPerimeterVertexInstance(struct FPolygonID PolygonID, int32_t PolygonVertexNumber); // Function EditableMesh.EditableMesh.GetPolygonPerimeterVertexInstance // (NetRequest|Static|NetMulticast|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	int32_t GetPolygonPerimeterVertexCount(struct FPolygonID PolygonID); // Function EditableMesh.EditableMesh.GetPolygonPerimeterVertexCount // (NetReliableExec|Native|Event|NetResponse|NetMulticast|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	struct FVertexID GetPolygonPerimeterVertex(struct FPolygonID PolygonID, int32_t PolygonVertexNumber); // Function EditableMesh.EditableMesh.GetPolygonPerimeterVertex // (Static|NetMulticast|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	void GetPolygonPerimeterEdges(struct FPolygonID PolygonID, struct TArray<struct FEdgeID>& OutPolygonPerimeterEdgeIDs); // Function EditableMesh.EditableMesh.GetPolygonPerimeterEdges // (Net|NetRequest|Exec|Native|Event|NetResponse|NetMulticast|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	int32_t GetPolygonPerimeterEdgeCount(struct FPolygonID PolygonID); // Function EditableMesh.EditableMesh.GetPolygonPerimeterEdgeCount // (NetReliableExec|Native|Event|NetResponse|NetMulticast|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	struct FEdgeID GetPolygonPerimeterEdge(struct FPolygonID PolygonID, int32_t PerimeterEdgeNumber, bool& bOutEdgeWindingIsReversedForPolygon); // Function EditableMesh.EditableMesh.GetPolygonPerimeterEdge // (NetReliableNetRequest|Native|Event|NetResponse|NetMulticast|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	struct FPolygonID GetPolygonInGroup(struct FPolygonGroupID PolygonGroupID, int32_t PolygonNumber); // Function EditableMesh.EditableMesh.GetPolygonInGroup // (Net|NetReliableNative|Event|NetResponse|NetMulticast|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	int32_t GetPolygonGroupCount(); // Function EditableMesh.EditableMesh.GetPolygonGroupCount // (NetReliableNative|Event|NetResponse|NetMulticast|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	int32_t GetPolygonCountInGroup(struct FPolygonGroupID PolygonGroupID); // Function EditableMesh.EditableMesh.GetPolygonCountInGroup // (Native|Event|NetResponse|NetMulticast|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	int32_t GetPolygonCount(); // Function EditableMesh.EditableMesh.GetPolygonCount // (Net|NetReliableNetRequest|Exec|Event|NetResponse|NetMulticast|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	void GetPolygonAdjacentPolygons(struct FPolygonID PolygonID, struct TArray<struct FPolygonID>& OutAdjacentPolygons); // Function EditableMesh.EditableMesh.GetPolygonAdjacentPolygons // (Net|NetReliableExec|Event|NetResponse|NetMulticast|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	struct FPolygonGroupID GetGroupForPolygon(struct FPolygonID PolygonID); // Function EditableMesh.EditableMesh.GetGroupForPolygon // (Net|Exec|Event|NetResponse|NetMulticast|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	struct FPolygonGroupID GetFirstValidPolygonGroup(); // Function EditableMesh.EditableMesh.GetFirstValidPolygonGroup // (Exec|Event|NetResponse|NetMulticast|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	void GetEdgeVertices(struct FEdgeID EdgeID, struct FVertexID& OutEdgeVertexID0, struct FVertexID& OutEdgeVertexID1); // Function EditableMesh.EditableMesh.GetEdgeVertices // (Net|NetReliableEvent|NetResponse|NetMulticast|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	struct FVertexID GetEdgeVertex(struct FEdgeID EdgeID, int32_t EdgeVertexNumber); // Function EditableMesh.EditableMesh.GetEdgeVertex // (Event|NetResponse|NetMulticast|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	struct FEdgeID GetEdgeThatConnectsVertices(struct FVertexID VertexID0, struct FVertexID VertexID1); // Function EditableMesh.EditableMesh.GetEdgeThatConnectsVertices // (NetRequest|Exec|Native|NetResponse|NetMulticast|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	void GetEdgeLoopElements(struct FEdgeID EdgeID, struct TArray<struct FEdgeID>& EdgeLoopIDs); // Function EditableMesh.EditableMesh.GetEdgeLoopElements // (Net|Exec|Native|NetResponse|NetMulticast|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	int32_t GetEdgeCount(); // Function EditableMesh.EditableMesh.GetEdgeCount // (Exec|Native|NetResponse|NetMulticast|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	void GetEdgeConnectedPolygons(struct FEdgeID EdgeID, struct TArray<struct FPolygonID>& OutConnectedPolygonIDs); // Function EditableMesh.EditableMesh.GetEdgeConnectedPolygons // (NetRequest|Native|NetResponse|NetMulticast|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	int32_t GetEdgeConnectedPolygonCount(struct FEdgeID EdgeID); // Function EditableMesh.EditableMesh.GetEdgeConnectedPolygonCount // (NetReliableNative|NetResponse|NetMulticast|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	struct FPolygonID GetEdgeConnectedPolygon(struct FEdgeID EdgeID, int32_t ConnectedPolygonNumber); // Function EditableMesh.EditableMesh.GetEdgeConnectedPolygon // (Net|NetReliableNetRequest|Exec|NetResponse|NetMulticast|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	void GeneratePolygonTangentsAndNormals(struct TArray<struct FPolygonID>& PolygonIDs); // Function EditableMesh.EditableMesh.GeneratePolygonTangentsAndNormals // (NetRequest|Exec|NetResponse|NetMulticast|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	void FlipPolygons(struct TArray<struct FPolygonID>& PolygonIDs); // Function EditableMesh.EditableMesh.FlipPolygons // (Net|Exec|NetResponse|NetMulticast|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	int32_t FindPolygonPerimeterVertexNumberForVertex(struct FPolygonID PolygonID, struct FVertexID VertexID); // Function EditableMesh.EditableMesh.FindPolygonPerimeterVertexNumberForVertex // (NetReliableNetRequest|NetResponse|NetMulticast|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	int32_t FindPolygonPerimeterEdgeNumberForVertices(struct FPolygonID PolygonID, struct FVertexID EdgeVertexID0, struct FVertexID EdgeVertexID1); // Function EditableMesh.EditableMesh.FindPolygonPerimeterEdgeNumberForVertices // (NetReliableNetResponse|NetMulticast|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	void FindPolygonLoop(struct FEdgeID EdgeID, struct TArray<struct FEdgeID>& OutEdgeLoopEdgeIDs, struct TArray<struct FEdgeID>& OutFlippedEdgeIDs, struct TArray<struct FEdgeID>& OutReversedEdgeIDPathToTake, struct TArray<struct FPolygonID>& OutPolygonIDsToSplit); // Function EditableMesh.EditableMesh.FindPolygonLoop // (Net|Exec|Native|Event|NetMulticast|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	void ExtrudePolygons(struct TArray<struct FPolygonID>& Polygons, float ExtrudeDistance, bool bKeepNeighborsTogether, struct TArray<struct FPolygonID>& OutNewExtrudedFrontPolygons); // Function EditableMesh.EditableMesh.ExtrudePolygons // (NetReliableNative|Event|NetMulticast|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	void ExtendVertices(struct TArray<struct FVertexID>& VertexIDs, bool bOnlyExtendClosestEdge, struct FVector ReferencePosition, struct TArray<struct FVertexID>& OutNewExtendedVertexIDs); // Function EditableMesh.EditableMesh.ExtendVertices // (NetRequest|Exec|Event|NetMulticast|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	void ExtendEdges(struct TArray<struct FEdgeID>& EdgeIDs, bool bWeldNeighbors, struct TArray<struct FEdgeID>& OutNewExtendedEdgeIDs); // Function EditableMesh.EditableMesh.ExtendEdges // (NetReliableNetRequest|Event|NetMulticast|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	void EndModification(bool bFromUndo); // Function EditableMesh.EditableMesh.EndModification // (NetRequest|Event|NetMulticast|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	void DeleteVertexInstances(struct TArray<struct FVertexInstanceID>& VertexInstanceIDsToDelete, bool bDeleteOrphanedVertices); // Function EditableMesh.EditableMesh.DeleteVertexInstances // (Event|NetMulticast|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	void DeleteVertexAndConnectedEdgesAndPolygons(struct FVertexID VertexID, bool bDeleteOrphanedEdges, bool bDeleteOrphanedVertices, bool bDeleteOrphanedVertexInstances, bool bDeleteEmptyPolygonGroups); // Function EditableMesh.EditableMesh.DeleteVertexAndConnectedEdgesAndPolygons // (Net|Exec|Native|NetMulticast|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	void DeletePolygons(struct TArray<struct FPolygonID>& PolygonIDsToDelete, bool bDeleteOrphanedEdges, bool bDeleteOrphanedVertices, bool bDeleteOrphanedVertexInstances, bool bDeleteEmptyPolygonGroups); // Function EditableMesh.EditableMesh.DeletePolygons // (NetReliableNative|NetMulticast|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	void DeletePolygonGroups(struct TArray<struct FPolygonGroupID>& PolygonGroupIDs); // Function EditableMesh.EditableMesh.DeletePolygonGroups // (Net|NetReliableNetRequest|Exec|NetMulticast|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	void DeleteOrphanVertices(struct TArray<struct FVertexID>& VertexIDsToDelete); // Function EditableMesh.EditableMesh.DeleteOrphanVertices // (NetRequest|Exec|NetMulticast|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	void DeleteEdges(struct TArray<struct FEdgeID>& EdgeIDsToDelete, bool bDeleteOrphanedVertices); // Function EditableMesh.EditableMesh.DeleteEdges // (Exec|NetMulticast|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	void DeleteEdgeAndConnectedPolygons(struct FEdgeID EdgeID, bool bDeleteOrphanedEdges, bool bDeleteOrphanedVertices, bool bDeleteOrphanedVertexInstances, bool bDeleteEmptyPolygonGroups); // Function EditableMesh.EditableMesh.DeleteEdgeAndConnectedPolygons // (Net|NetMulticast|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	void CreateVertices(struct TArray<struct FVertexToCreate>& VerticesToCreate, struct TArray<struct FVertexID>& OutNewVertexIDs); // Function EditableMesh.EditableMesh.CreateVertices // (NetRequest|Exec|Native|Event|NetResponse|Static|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	void CreateVertexInstances(struct TArray<struct FVertexInstanceToCreate>& VertexInstancesToCreate, struct TArray<struct FVertexInstanceID>& OutNewVertexInstanceIDs); // Function EditableMesh.EditableMesh.CreateVertexInstances // (Net|NetReliableNetRequest|Native|Event|NetResponse|Static|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	void CreatePolygons(struct TArray<struct FPolygonToCreate>& PolygonsToCreate, struct TArray<struct FPolygonID>& OutNewPolygonIDs, struct TArray<struct FEdgeID>& OutNewEdgeIDs); // Function EditableMesh.EditableMesh.CreatePolygons // (Native|Event|NetResponse|Static|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	void CreatePolygonGroups(struct TArray<struct FPolygonGroupToCreate>& PolygonGroupsToCreate, struct TArray<struct FPolygonGroupID>& OutNewPolygonGroupIDs); // Function EditableMesh.EditableMesh.CreatePolygonGroups // (Net|NetReliableExec|Event|NetResponse|Static|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	void CreateMissingPolygonPerimeterEdges(struct FPolygonID PolygonID, struct TArray<struct FEdgeID>& OutNewEdgeIDs); // Function EditableMesh.EditableMesh.CreateMissingPolygonPerimeterEdges // (Net|NetReliableNetRequest|Event|NetResponse|Static|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	void CreateEmptyVertexRange(int32_t NumVerticesToCreate, struct TArray<struct FVertexID>& OutNewVertexIDs); // Function EditableMesh.EditableMesh.CreateEmptyVertexRange // (NetRequest|Event|NetResponse|Static|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	void CreateEdges(struct TArray<struct FEdgeToCreate>& EdgesToCreate, struct TArray<struct FEdgeID>& OutNewEdgeIDs); // Function EditableMesh.EditableMesh.CreateEdges // (Net|NetReliableNetRequest|Exec|Native|NetResponse|Static|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	void ComputePolygonsSharedEdges(struct TArray<struct FPolygonID>& PolygonIDs, struct TArray<struct FEdgeID>& OutSharedEdgeIDs); // Function EditableMesh.EditableMesh.ComputePolygonsSharedEdges // (NetReliableExec|Native|NetResponse|Static|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	struct FPlane ComputePolygonPlane(struct FPolygonID PolygonID); // Function EditableMesh.EditableMesh.ComputePolygonPlane // (Exec|Native|NetResponse|Static|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	struct FVector ComputePolygonNormal(struct FPolygonID PolygonID); // Function EditableMesh.EditableMesh.ComputePolygonNormal // (Net|NetRequest|Native|NetResponse|Static|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	struct FVector ComputePolygonCenter(struct FPolygonID PolygonID); // Function EditableMesh.EditableMesh.ComputePolygonCenter // (Net|NetReliableNative|NetResponse|Static|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	struct FBoxSphereBounds ComputeBoundingBoxAndSphere(); // Function EditableMesh.EditableMesh.ComputeBoundingBoxAndSphere // (NetReliableNative|NetResponse|Static|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	struct FBox ComputeBoundingBox(); // Function EditableMesh.EditableMesh.ComputeBoundingBox // (Native|NetResponse|Static|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	struct UEditableMesh* CommitInstance(struct UPrimitiveComponent* ComponentToInstanceTo); // Function EditableMesh.EditableMesh.CommitInstance // (NetReliableNetRequest|Exec|NetResponse|Static|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	void Commit(); // Function EditableMesh.EditableMesh.Commit // (NetReliableNetRequest|Exec|NetResponse|Static|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	void ChangePolygonsVertexInstances(struct TArray<struct FChangeVertexInstancesForPolygon>& VertexInstancesForPolygons); // Function EditableMesh.EditableMesh.ChangePolygonsVertexInstances // (Net|Exec|NetResponse|Static|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	void BevelPolygons(struct TArray<struct FPolygonID>& PolygonIDs, float BevelFixedDistance, float BevelProgressTowardCenter, struct TArray<struct FPolygonID>& OutNewCenterPolygonIDs, struct TArray<struct FPolygonID>& OutNewSidePolygonIDs); // Function EditableMesh.EditableMesh.BevelPolygons // (NetReliableNetResponse|Static|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	void AssignPolygonsToPolygonGroups(struct TArray<struct FPolygonGroupForPolygon>& PolygonGroupForPolygons, bool bDeleteOrphanedPolygonGroups); // Function EditableMesh.EditableMesh.AssignPolygonsToPolygonGroups // (NetReliableNetRequest|Exec|Native|Event|Static|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
	bool AnyChangesToUndo(); // Function EditableMesh.EditableMesh.AnyChangesToUndo // (Net|NetRequest|Exec|Native|Event|Static|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145ce80
};

// Class EditableMesh.EditableMeshFactory
// Size: 0x28 (Inherited: 0x28)
struct UEditableMeshFactory : UObject {

	struct UEditableMesh* MakeEditableMesh(struct UPrimitiveComponent* PrimitiveComponent, int32_t LODIndex); // Function EditableMesh.EditableMeshFactory.MakeEditableMesh // (Net|Exec|Native|NetMulticast|UbergraphFunction|MulticastDelegate|Public|Protected|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f3145c580
};

// Class EditableMesh.EditableStaticMeshAdapter
// Size: 0xe0 (Inherited: 0x28)
struct UEditableStaticMeshAdapter : UEditableMeshAdapter {
	struct UStaticMesh* StaticMesh; // 0x28(0x08)
	struct UStaticMesh* OriginalStaticMesh; // 0x30(0x08)
	int32_t StaticMeshLODIndex; // 0x38(0x04)
	char pad_3C[0xa4]; // 0x3c(0xa4)
};

