// Class LimNative.LimNative
// Size: 0x3f0 (Inherited: 0x28)
struct ULimNative : UObject {
	bool ShowLog; // 0x28(0x01)
	char pad_29[0x7]; // 0x29(0x07)
	struct FMulticastInlineDelegate OnLog; // 0x30(0x10)
	struct FMulticastInlineDelegate OnEvent; // 0x40(0x10)
	struct FMulticastInlineDelegate OnGetLanguage; // 0x50(0x10)
	struct FMulticastInlineDelegate OnSetLanguage; // 0x60(0x10)
	struct FMulticastInlineDelegate OnSetAllConfig; // 0x70(0x10)
	struct FMulticastInlineDelegate OnSetReportConfig; // 0x80(0x10)
	struct FMulticastInlineDelegate OnSetParkConfig; // 0x90(0x10)
	struct FMulticastInlineDelegate OnGetResDir; // 0xa0(0x10)
	struct FMulticastInlineDelegate OnSetResDir; // 0xb0(0x10)
	struct FMulticastInlineDelegate OnLogin; // 0xc0(0x10)
	struct FMulticastInlineDelegate OnLoginV2; // 0xd0(0x10)
	struct FMulticastInlineDelegate OnLogout; // 0xe0(0x10)
	struct FMulticastInlineDelegate OnCreateGroup; // 0xf0(0x10)
	struct FMulticastInlineDelegate OnJoinGroup; // 0x100(0x10)
	struct FMulticastInlineDelegate OnQuitGroup; // 0x110(0x10)
	struct FMulticastInlineDelegate OnDestoryGroup; // 0x120(0x10)
	struct FMulticastInlineDelegate OnGetGroup; // 0x130(0x10)
	struct FMulticastInlineDelegate OnGetGroups; // 0x140(0x10)
	struct FMulticastInlineDelegate OnGetAttr; // 0x150(0x10)
	struct FMulticastInlineDelegate OnGetAllGroupAttr; // 0x160(0x10)
	struct FMulticastInlineDelegate OnSetGroupAttr; // 0x170(0x10)
	struct FMulticastInlineDelegate OnGetGroupMembers; // 0x180(0x10)
	struct FMulticastInlineDelegate OnAddGroupMember; // 0x190(0x10)
	struct FMulticastInlineDelegate OnRemoveGroupMember; // 0x1a0(0x10)
	struct FMulticastInlineDelegate OnGetGroupMember; // 0x1b0(0x10)
	struct FMulticastInlineDelegate OnSetConvRead; // 0x1c0(0x10)
	struct FMulticastInlineDelegate OnSendMsg; // 0x1d0(0x10)
	struct FMulticastInlineDelegate OnRevokeMsg; // 0x1e0(0x10)
	struct FMulticastInlineDelegate OnGetBeforeMsg; // 0x1f0(0x10)
	struct FMulticastInlineDelegate OnGetAfterMsg; // 0x200(0x10)
	struct FMulticastInlineDelegate OnGetMsgsById; // 0x210(0x10)
	struct FMulticastInlineDelegate OnGetCommonMsgs; // 0x220(0x10)
	struct FMulticastInlineDelegate OnSetMsgState; // 0x230(0x10)
	struct FMulticastInlineDelegate OnConvHandle; // 0x240(0x10)
	struct FMulticastInlineDelegate OnConvsGet; // 0x250(0x10)
	struct FMulticastInlineDelegate OnGetFriends; // 0x260(0x10)
	struct FMulticastInlineDelegate OnRemoveFriend; // 0x270(0x10)
	struct FMulticastInlineDelegate OnCreateFriendRequest; // 0x280(0x10)
	struct FMulticastInlineDelegate OnGetFriendRequests; // 0x290(0x10)
	struct FMulticastInlineDelegate OnAcceptFriendRequest; // 0x2a0(0x10)
	struct FMulticastInlineDelegate OnRefuseFriendRequest; // 0x2b0(0x10)
	struct FMulticastInlineDelegate OnCancelFriendRequest; // 0x2c0(0x10)
	struct FMulticastInlineDelegate OnGetBlockees; // 0x2d0(0x10)
	struct FMulticastInlineDelegate OnAddToBlockee; // 0x2e0(0x10)
	struct FMulticastInlineDelegate OnRemoveFromBlockee; // 0x2f0(0x10)
	struct FMulticastInlineDelegate OnGetUser; // 0x300(0x10)
	struct FMulticastInlineDelegate OnGetUsers; // 0x310(0x10)
	struct FMulticastInlineDelegate OnGetUsersState; // 0x320(0x10)
	struct FMulticastInlineDelegate OnReportMsg; // 0x330(0x10)
	struct FMulticastInlineDelegate OnTranslateText; // 0x340(0x10)
	struct FMulticastInlineDelegate OnCheckImage; // 0x350(0x10)
	struct FMulticastInlineDelegate OnGetOssToken; // 0x360(0x10)
	struct FMulticastInlineDelegate OnGetGMEToken; // 0x370(0x10)
	struct FMulticastInlineDelegate OnMsgReceived; // 0x380(0x10)
	struct FMulticastInlineDelegate OnMsgLogicReceived; // 0x390(0x10)
	struct FMulticastInlineDelegate OnMsgRevoked; // 0x3a0(0x10)
	struct FMulticastInlineDelegate OnGetMiscConfigInfo; // 0x3b0(0x10)
	struct FMulticastInlineDelegate OnGetConvChatLevelConfig; // 0x3c0(0x10)
	struct FMulticastInlineDelegate OnGetConnState; // 0x3d0(0x10)
	struct FMulticastInlineDelegate OnNetState; // 0x3e0(0x10)

	void TranslateText(struct FLimNativeLowLevelWrapper& InCtx, struct FString InText, enum class ELimNativeSupportedLanguage InLang); // Function LimNative.LimNative.TranslateText // (Exec|NetResponse|Static|NetMulticast|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31460880
	void SetResDir(struct FLimNativeLowLevelWrapper& InCtx, struct FString InResDir); // Function LimNative.LimNative.SetResDir // (NetRequest|NetResponse|Static|NetMulticast|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467fc0
	void SetMsgState(struct FLimNativeLowLevelWrapper& InCtx, struct FLimNativeSetMsgState& SetMsgParams); // Function LimNative.LimNative.SetMsgState // (NetReliableNetRequest|Exec|Native|Event|Static|NetMulticast|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f32810d20
	void SetLogHandler(struct FLimNativeLowLevelWrapper& InCtx); // Function LimNative.LimNative.SetLogHandler // (Net|NetReliableExec|Native|Event|Static|NetMulticast|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467fc0
	void SetLanguage(struct FLimNativeLowLevelWrapper& InCtx, enum class ELimNativeSupportedLanguage InLanguage); // Function LimNative.LimNative.SetLanguage // (Net|NetReliableNetRequest|Native|Event|Static|NetMulticast|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467fc0
	void SetGroupAttr(struct FLimNativeLowLevelWrapper& InCtx, struct FString groupid, struct FString Key, struct FString Value); // Function LimNative.LimNative.SetGroupAttr // (Net|Native|Event|Static|NetMulticast|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467fc0
	void SetEventHandler(struct FLimNativeLowLevelWrapper& InCtx); // Function LimNative.LimNative.SetEventHandler // (NetReliableNetRequest|Exec|Event|Static|NetMulticast|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467fc0
	void SetConvRead(struct FLimNativeLowLevelWrapper& InCtx, struct FString ConvID, enum class ELimNativeConvType ConvType, struct FString InMsgID, struct FString Extra); // Function LimNative.LimNative.SetConvRead // (NetReliableNetRequest|Event|Static|NetMulticast|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467fc0
	void SetAllConfig(struct FLimNativeLowLevelWrapper& InCtx, struct FLimNativeInitConfig InConfig); // Function LimNative.LimNative.SetAllConfig // (NetRequest|Exec|Native|Static|NetMulticast|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467fc0
	void SendVoiceMsg(struct FLimNativeLowLevelWrapper& InCtx, struct FLimNativeIMVoiceMessage& VoiceMsg, struct FString ConvID, enum class ELimNativeConvType ConvType, struct FString Nonce, struct FString Timestamp, struct FString Extra); // Function LimNative.LimNative.SendVoiceMsg // (NetReliableNetRequest|Exec|Static|NetMulticast|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467fc0
	void SendTextWithAtMsg(struct FLimNativeLowLevelWrapper& InCtx, struct FLimNativeIMTextWithAtMessage& TextWithAtMsg, struct FString ConvID, enum class ELimNativeConvType ConvType, struct FString Nonce, struct FString Timestamp, struct FString Extra); // Function LimNative.LimNative.SendTextWithAtMsg // (Net|Static|NetMulticast|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467fc0
	void SendTextMsg(struct FLimNativeLowLevelWrapper& InCtx, struct FLimNativeIMTextMessage& TextMsg, struct FString ConvID, enum class ELimNativeConvType ConvType, struct FString Nonce, struct FString Timestamp, struct FString Extra); // Function LimNative.LimNative.SendTextMsg // (NetRequest|Native|Event|NetResponse|NetMulticast|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467fc0
	void SendShareMsg(struct FLimNativeLowLevelWrapper& InCtx, struct FLimNativeIMShareMessage& ShareMsg, struct FString ConvID, enum class ELimNativeConvType ConvType, struct FString Nonce, struct FString Timestamp, struct FString Extra); // Function LimNative.LimNative.SendShareMsg // (NetReliableNetRequest|Event|NetResponse|NetMulticast|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467fc0
	void SendImageMsg(struct FLimNativeLowLevelWrapper& InCtx, struct FLimNativeIMImageMessage& ImageMsg, struct FString ConvID, enum class ELimNativeConvType ConvType, struct FString Nonce, struct FString Timestamp, struct FString Extra); // Function LimNative.LimNative.SendImageMsg // (Net|NetReliableNetRequest|Native|NetResponse|NetMulticast|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467fc0
	void SendEmotionMsg(struct FLimNativeLowLevelWrapper& InCtx, struct FLimNativeIMEmotionMessage& EmotionMsg, struct FString ConvID, enum class ELimNativeConvType ConvType, struct FString Nonce, struct FString Timestamp, struct FString Extra); // Function LimNative.LimNative.SendEmotionMsg // (Net|Exec|NetResponse|NetMulticast|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467fc0
	void RevokeVoiceMsg(struct FLimNativeLowLevelWrapper& InCtx, struct FLimNativeIMVoiceMessage& VoiceMsg, struct FString ConvID, enum class ELimNativeConvType ConvType, struct FString Nonce, struct FString Timestamp); // Function LimNative.LimNative.RevokeVoiceMsg // (Net|NetRequest|Exec|Native|Event|NetMulticast|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f32810d20
	void RevokeTextWithAtMsg(struct FLimNativeLowLevelWrapper& InCtx, struct FLimNativeIMTextWithAtMessage& TextWithAtMsg, struct FString ConvID, enum class ELimNativeConvType ConvType, struct FString Nonce, struct FString Timestamp); // Function LimNative.LimNative.RevokeTextWithAtMsg // (Net|Native|Event|NetMulticast|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f32810d20
	void RevokeTextMsg(struct FLimNativeLowLevelWrapper& InCtx, struct FLimNativeIMTextMessage& TextMsg, struct FString ConvID, enum class ELimNativeConvType ConvType, struct FString Nonce, struct FString Timestamp); // Function LimNative.LimNative.RevokeTextMsg // (NetReliableNetRequest|Event|NetMulticast|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f32810d20
	void RevokeShareMsg(struct FLimNativeLowLevelWrapper& InCtx, struct FLimNativeIMShareMessage& ShareMsg, struct FString ConvID, enum class ELimNativeConvType ConvType, struct FString Nonce, struct FString Timestamp); // Function LimNative.LimNative.RevokeShareMsg // (Exec|Native|NetMulticast|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f32810d20
	void RevokeImageMsg(struct FLimNativeLowLevelWrapper& InCtx, struct FLimNativeIMImageMessage& ImageMsg, struct FString ConvID, enum class ELimNativeConvType ConvType, struct FString Nonce, struct FString Timestamp); // Function LimNative.LimNative.RevokeImageMsg // (Net|NetReliableExec|NetMulticast|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f32810d20
	void RevokeEmotionMsg(struct FLimNativeLowLevelWrapper& InCtx, struct FLimNativeIMEmotionMessage& EmotionMsg, struct FString ConvID, enum class ELimNativeConvType ConvType, struct FString Nonce, struct FString Timestamp); // Function LimNative.LimNative.RevokeEmotionMsg // (NetReliableNetRequest|Exec|Native|Event|NetResponse|Static|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f32810d20
	void ReportMsg(struct FLimNativeLowLevelWrapper& InCtx, struct FString InType, struct FString InMsg); // Function LimNative.LimNative.ReportMsg // (Exec|Native|Event|NetResponse|Static|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467fc0
	void RemoveGroupMember(struct FLimNativeLowLevelWrapper& InCtx, struct FString groupid, struct FString memberid); // Function LimNative.LimNative.RemoveGroupMember // (NetReliableNative|Event|NetResponse|Static|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467fc0
	void RemoveFromBlockee(struct FLimNativeLowLevelWrapper& InCtx, struct FString InUserId); // Function LimNative.LimNative.RemoveFromBlockee // (NetReliableNetRequest|Exec|Event|NetResponse|Static|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467fc0
	void RemoveFriend(struct FLimNativeLowLevelWrapper& InCtx, struct FString InUserId, struct FString InExtra); // Function LimNative.LimNative.RemoveFriend // (Exec|Event|NetResponse|Static|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467fc0
	void RefuseFriendRequest(struct FLimNativeLowLevelWrapper& InCtx, struct FString InRequestID, struct FString InExtra); // Function LimNative.LimNative.RefuseFriendRequest // (NetReliableEvent|NetResponse|Static|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467fc0
	void QuitGroup(struct FLimNativeLowLevelWrapper& InCtx, struct FString groupid); // Function LimNative.LimNative.QuitGroup // (NetReliableNetRequest|Exec|Native|NetResponse|Static|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467fc0
	void PostInitLIM(struct FLimNativeLowLevelWrapper& ctx, struct FLimNativeReportConfig ReportConfig, struct FLimNativeParkConfig ParkConfig); // Function LimNative.LimNative.PostInitLIM // (Net|NetReliableNetRequest|Exec|Native|Event|Static|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467fc0
	void MsgsGetCommon(struct FLimNativeLowLevelWrapper& InCtx); // Function LimNative.LimNative.MsgsGetCommon // (NetRequest|Exec|Native|Event|Static|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467fc0
	void Logout(struct FLimNativeLowLevelWrapper& InCtx); // Function LimNative.LimNative.Logout // (NetReliableExec|Native|Event|Static|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467fc0
	void LoginV2(struct FLimNativeLowLevelWrapper& InCtx, struct FString InEnvId, struct FString InRoleID); // Function LimNative.LimNative.LoginV2 // (NetRequest|Native|Event|Static|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467fc0
	void Login(struct FLimNativeLowLevelWrapper& InCtx, struct FString InAppId, struct FString InAppUserID, struct FString InToken, struct FString InRoleID, struct FString InExtra); // Function LimNative.LimNative.Login // (NetReliableExec|Event|Static|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467fc0
	void LIMOnTranslateTextDynamicDelegate__DelegateSignature(struct FLimNativeLowLevelWrapper& InWrapper, struct FLimNativeDataCallBackBase& RetData); // DelegateFunction LimNative.LimNative.LIMOnTranslateTextDynamicDelegate__DelegateSignature // (Net|Exec|Event|NetResponse|UbergraphFunction|MulticastDelegate|NetServer|HasDefaults|NetClient|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467fc0
	void LIMOnSetResDirDynamicDelegate__DelegateSignature(struct FLimNativeLowLevelWrapper& InWrapper, struct FLimNativeResDirConfig& RetData); // DelegateFunction LimNative.LimNative.LIMOnSetResDirDynamicDelegate__DelegateSignature // (Net|Exec|Event|NetResponse|UbergraphFunction|MulticastDelegate|NetServer|HasDefaults|NetClient|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f32810d20
	void LIMOnSetReportConfigDynamicDelegate__DelegateSignature(struct FLimNativeLowLevelWrapper& InWrapper, struct FLimNativeReportConfig& RetData); // DelegateFunction LimNative.LimNative.LIMOnSetReportConfigDynamicDelegate__DelegateSignature // (Net|Exec|Event|NetResponse|UbergraphFunction|MulticastDelegate|NetServer|HasDefaults|NetClient|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f32810d20
	void LIMOnSetParkConfigDynamicDelegate__DelegateSignature(struct FLimNativeLowLevelWrapper& InWrapper, struct FLimNativeParkConfig& RetData); // DelegateFunction LimNative.LimNative.LIMOnSetParkConfigDynamicDelegate__DelegateSignature // (Net|Exec|Event|NetResponse|UbergraphFunction|MulticastDelegate|NetServer|HasDefaults|NetClient|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f32810d20
	void LIMOnSetMsgStateDynamicDelegate__DelegateSignature(struct FLimNativeLowLevelWrapper& InWrapper, struct FLimNativeOnSetMsgStateCallBack& RetData); // DelegateFunction LimNative.LimNative.LIMOnSetMsgStateDynamicDelegate__DelegateSignature // (Net|Exec|Event|NetResponse|UbergraphFunction|MulticastDelegate|NetServer|HasDefaults|NetClient|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f32810d20
	void LIMOnSetLanguageDynamicDelegate__DelegateSignature(struct FLimNativeLowLevelWrapper& InWrapper, struct FLimNativeLanguageConfig& RetData); // DelegateFunction LimNative.LimNative.LIMOnSetLanguageDynamicDelegate__DelegateSignature // (Net|Exec|Event|NetResponse|UbergraphFunction|MulticastDelegate|NetServer|HasDefaults|NetClient|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f32810d20
	void LIMOnSetGroupAttrDynamicDelegate__DelegateSignature(struct FLimNativeLowLevelWrapper& InWrapper, struct FLimNativeOnGroupAttrSetCallBack& RetData); // DelegateFunction LimNative.LimNative.LIMOnSetGroupAttrDynamicDelegate__DelegateSignature // (Net|Exec|Event|NetResponse|UbergraphFunction|MulticastDelegate|NetServer|HasDefaults|NetClient|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f32810d20
	void LIMOnSetConvReadDynamicDelegate__DelegateSignature(struct FLimNativeLowLevelWrapper& InWrapper, struct FLimNativeOnSetConvReadCallBack& RetData); // DelegateFunction LimNative.LimNative.LIMOnSetConvReadDynamicDelegate__DelegateSignature // (Net|Exec|Event|NetResponse|UbergraphFunction|MulticastDelegate|NetServer|HasDefaults|NetClient|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f32810d20
	void LIMOnSetAllConfigDynamicDelegate__DelegateSignature(struct FLimNativeLowLevelWrapper& InWrapper, struct FLimNativeInitConfig& RetData); // DelegateFunction LimNative.LimNative.LIMOnSetAllConfigDynamicDelegate__DelegateSignature // (Net|Exec|Event|NetResponse|UbergraphFunction|MulticastDelegate|NetServer|HasDefaults|NetClient|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467fc0
	void LIMOnSendMsgDynamicDelegate__DelegateSignature(struct FLimNativeLowLevelWrapper& InWrapper, struct FLimNativeOnSendMsgCallBack& RetData); // DelegateFunction LimNative.LimNative.LIMOnSendMsgDynamicDelegate__DelegateSignature // (Net|Exec|Event|NetResponse|UbergraphFunction|MulticastDelegate|NetServer|HasDefaults|NetClient|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f32810d20
	void LIMOnRevokeMsgDynamicDelegate__DelegateSignature(struct FLimNativeLowLevelWrapper& InWrapper, struct FLimNativeOnRevokeMsgCallBack& RetData); // DelegateFunction LimNative.LimNative.LIMOnRevokeMsgDynamicDelegate__DelegateSignature // (Net|Exec|Event|NetResponse|UbergraphFunction|MulticastDelegate|NetServer|HasDefaults|NetClient|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f32810d20
	void LIMOnReportMsgDynamicDelegate__DelegateSignature(struct FLimNativeLowLevelWrapper& InWrapper, struct FLimNativeDataCallBackBase& RetData); // DelegateFunction LimNative.LimNative.LIMOnReportMsgDynamicDelegate__DelegateSignature // (Net|Exec|Event|NetResponse|UbergraphFunction|MulticastDelegate|NetServer|HasDefaults|NetClient|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467fc0
	void LIMOnRemoveGroupMemberDynamicDelegate__DelegateSignature(struct FLimNativeLowLevelWrapper& InWrapper, struct FLimNativeOnGroupMemberRemoveCallBack& RetData); // DelegateFunction LimNative.LimNative.LIMOnRemoveGroupMemberDynamicDelegate__DelegateSignature // (Net|Exec|Event|NetResponse|UbergraphFunction|MulticastDelegate|NetServer|HasDefaults|NetClient|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f32810d20
	void LIMOnRemoveFromBlockeeDynamicDelegate__DelegateSignature(struct FLimNativeLowLevelWrapper& InWrapper, struct FLimNativeFriendCommonCallBack& RetData); // DelegateFunction LimNative.LimNative.LIMOnRemoveFromBlockeeDynamicDelegate__DelegateSignature // (Net|Exec|Event|NetResponse|UbergraphFunction|MulticastDelegate|NetServer|HasDefaults|NetClient|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467fc0
	void LIMOnRemoveFriendDynamicDelegate__DelegateSignature(struct FLimNativeLowLevelWrapper& InWrapper, struct FLimNativeFriendCommonCallBack& RetData); // DelegateFunction LimNative.LimNative.LIMOnRemoveFriendDynamicDelegate__DelegateSignature // (Net|Exec|Event|NetResponse|UbergraphFunction|MulticastDelegate|NetServer|HasDefaults|NetClient|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467fc0
	void LIMOnRefuseFriendRequestDynamicDelegate__DelegateSignature(struct FLimNativeLowLevelWrapper& InWrapper, struct FLimNativeFriendCommonCallBack& RetData); // DelegateFunction LimNative.LimNative.LIMOnRefuseFriendRequestDynamicDelegate__DelegateSignature // (Net|Exec|Event|NetResponse|UbergraphFunction|MulticastDelegate|NetServer|HasDefaults|NetClient|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467fc0
	void LIMOnQuitGroupDynamicDelegate__DelegateSignature(struct FLimNativeLowLevelWrapper& InWrapper, struct FLimNativeOnGroupQuitCallBack& RetData); // DelegateFunction LimNative.LimNative.LIMOnQuitGroupDynamicDelegate__DelegateSignature // (Net|Exec|Event|NetResponse|UbergraphFunction|MulticastDelegate|NetServer|HasDefaults|NetClient|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f32810d20
	void LIMOnNetConnectStateDynamicDelegate__DelegateSignature(struct FLimNativeLowLevelWrapper& InWrapper, int32_t EventCode); // DelegateFunction LimNative.LimNative.LIMOnNetConnectStateDynamicDelegate__DelegateSignature // (Net|Exec|Event|NetResponse|UbergraphFunction|MulticastDelegate|NetServer|HasDefaults|NetClient|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467fc0
	void LIMOnMsgRevokedDynamicDelegate__DelegateSignature(struct FLimNativeLowLevelWrapper& InWrapper, struct FLimNativeOnMsgRevokedEventCallBack& RetData); // DelegateFunction LimNative.LimNative.LIMOnMsgRevokedDynamicDelegate__DelegateSignature // (Net|Exec|Event|NetResponse|UbergraphFunction|MulticastDelegate|NetServer|HasDefaults|NetClient|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f32810d20
	void LIMOnMsgReceivedDynamicDelegate__DelegateSignature(struct FLimNativeLowLevelWrapper& InWrapper, struct FLimNativeOnMsgReceivedEventCallBack& RetData); // DelegateFunction LimNative.LimNative.LIMOnMsgReceivedDynamicDelegate__DelegateSignature // (Net|Exec|Event|NetResponse|UbergraphFunction|MulticastDelegate|NetServer|HasDefaults|NetClient|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f32810d20
	void LIMOnMsgLogicReceivedDynamicDelegate__DelegateSignature(struct FLimNativeLowLevelWrapper& InWrapper, struct FLimNativeOnMsgLogicReceivedEventCallBack& RetData); // DelegateFunction LimNative.LimNative.LIMOnMsgLogicReceivedDynamicDelegate__DelegateSignature // (Net|Exec|Event|NetResponse|UbergraphFunction|MulticastDelegate|NetServer|HasDefaults|NetClient|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f32810d20
	void LIMOnLogoutDynamicDelegate__DelegateSignature(struct FLimNativeLowLevelWrapper& InWrapper, struct FLimNativeOnLogoutCallBack& RetData); // DelegateFunction LimNative.LimNative.LIMOnLogoutDynamicDelegate__DelegateSignature // (Net|Exec|Event|NetResponse|UbergraphFunction|MulticastDelegate|NetServer|HasDefaults|NetClient|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f32810d20
	void LIMOnLoginDynamicDelegate__DelegateSignature(struct FLimNativeLowLevelWrapper& InWrapper, struct FLimNativeOnLoginCallBack& RetData); // DelegateFunction LimNative.LimNative.LIMOnLoginDynamicDelegate__DelegateSignature // (Net|Exec|Event|NetResponse|UbergraphFunction|MulticastDelegate|NetServer|HasDefaults|NetClient|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f32810d20
	void LIMOnJoinGroupDynamicDelegate__DelegateSignature(struct FLimNativeLowLevelWrapper& InWrapper, struct FLimNativeOnGroupJoinCallBack& RetData); // DelegateFunction LimNative.LimNative.LIMOnJoinGroupDynamicDelegate__DelegateSignature // (Net|Exec|Event|NetResponse|UbergraphFunction|MulticastDelegate|NetServer|HasDefaults|NetClient|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f32810d20
	void LIMOnGetUsersStateDynamicDelegate__DelegateSignature(struct FLimNativeLowLevelWrapper& InWrapper, struct FLimNativeOnGetUsersStateCallBack& RetData); // DelegateFunction LimNative.LimNative.LIMOnGetUsersStateDynamicDelegate__DelegateSignature // (Net|Exec|Event|NetResponse|UbergraphFunction|MulticastDelegate|NetServer|HasDefaults|NetClient|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f32810d20
	void LIMOnGetUsersDynamicDelegate__DelegateSignature(struct FLimNativeLowLevelWrapper& InWrapper, struct FLimNativeOnGetUsersCallBack& RetData); // DelegateFunction LimNative.LimNative.LIMOnGetUsersDynamicDelegate__DelegateSignature // (Net|Exec|Event|NetResponse|UbergraphFunction|MulticastDelegate|NetServer|HasDefaults|NetClient|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f32810d20
	void LIMOnGetUserDynamicDelegate__DelegateSignature(struct FLimNativeLowLevelWrapper& InWrapper, struct FLimNativeOnGetUserCallBack& RetData); // DelegateFunction LimNative.LimNative.LIMOnGetUserDynamicDelegate__DelegateSignature // (Net|Exec|Event|NetResponse|UbergraphFunction|MulticastDelegate|NetServer|HasDefaults|NetClient|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f32810d20
	void LIMOnGetOssTokenDynamicDelegate__DelegateSignature(struct FLimNativeLowLevelWrapper& InWrapper, struct FLimNativeGetOssTokenCallBack& RetData); // DelegateFunction LimNative.LimNative.LIMOnGetOssTokenDynamicDelegate__DelegateSignature // (Net|Exec|Event|NetResponse|UbergraphFunction|MulticastDelegate|NetServer|HasDefaults|NetClient|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f32810d20
	void LIMOnGetMsgsDynamicDelegate__DelegateSignature(struct FLimNativeLowLevelWrapper& InWrapper, struct FLimNativeOnGetMsgsCallBack& RetData); // DelegateFunction LimNative.LimNative.LIMOnGetMsgsDynamicDelegate__DelegateSignature // (Net|Exec|Event|NetResponse|UbergraphFunction|MulticastDelegate|NetServer|HasDefaults|NetClient|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f32810d20
	void LIMOnGetMiscConfigInfoDynamicDelegate__DelegateSignature(struct FLimNativeLowLevelWrapper& InWrapper, struct FLimNativeGetMiscConfigInfoCallBack& RetData); // DelegateFunction LimNative.LimNative.LIMOnGetMiscConfigInfoDynamicDelegate__DelegateSignature // (Net|Exec|Event|NetResponse|UbergraphFunction|MulticastDelegate|NetServer|HasDefaults|NetClient|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f32810d20
	void LIMOnGetGroupsDynamicDelegate__DelegateSignature(struct FLimNativeLowLevelWrapper& InWrapper, struct FLimNativeOnGroupsGetCallBack& RetData); // DelegateFunction LimNative.LimNative.LIMOnGetGroupsDynamicDelegate__DelegateSignature // (Net|Exec|Event|NetResponse|UbergraphFunction|MulticastDelegate|NetServer|HasDefaults|NetClient|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f32810d20
	void LIMOnGetGroupMembersDynamicDelegate__DelegateSignature(struct FLimNativeLowLevelWrapper& InWrapper, struct FLimNativeOnGroupMembersGetCallBack& RetData); // DelegateFunction LimNative.LimNative.LIMOnGetGroupMembersDynamicDelegate__DelegateSignature // (Net|Exec|Event|NetResponse|UbergraphFunction|MulticastDelegate|NetServer|HasDefaults|NetClient|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f32810d20
	void LIMOnGetGroupMemberDynamicDelegate__DelegateSignature(struct FLimNativeLowLevelWrapper& InWrapper, struct FLimNativeOnGroupMemberGetCallBack& RetData); // DelegateFunction LimNative.LimNative.LIMOnGetGroupMemberDynamicDelegate__DelegateSignature // (Net|Exec|Event|NetResponse|UbergraphFunction|MulticastDelegate|NetServer|HasDefaults|NetClient|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f32810d20
	void LIMOnGetGroupDynamicDelegate__DelegateSignature(struct FLimNativeLowLevelWrapper& InWrapper, struct FLimNativeOnGroupGetCallBack& RetData); // DelegateFunction LimNative.LimNative.LIMOnGetGroupDynamicDelegate__DelegateSignature // (Net|Exec|Event|NetResponse|UbergraphFunction|MulticastDelegate|NetServer|HasDefaults|NetClient|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f32810d20
	void LIMOnGetGroupAttrDynamicDelegate__DelegateSignature(struct FLimNativeLowLevelWrapper& InWrapper, struct FLimNativeOnGroupAttrGetCallBack& RetData); // DelegateFunction LimNative.LimNative.LIMOnGetGroupAttrDynamicDelegate__DelegateSignature // (Net|Exec|Event|NetResponse|UbergraphFunction|MulticastDelegate|NetServer|HasDefaults|NetClient|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f32810d20
	void LIMOnGetGMETokenDynamicDelegate__DelegateSignature(struct FLimNativeLowLevelWrapper& InWrapper, struct FLimNativeGetGMETokenCallBack& RetData); // DelegateFunction LimNative.LimNative.LIMOnGetGMETokenDynamicDelegate__DelegateSignature // (Net|Exec|Event|NetResponse|UbergraphFunction|MulticastDelegate|NetServer|HasDefaults|NetClient|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f32810d20
	void LIMOnGetFriendsDynamicDelegate__DelegateSignature(struct FLimNativeLowLevelWrapper& InWrapper, struct FLimNativeOnGetFriendCallBack& RetData); // DelegateFunction LimNative.LimNative.LIMOnGetFriendsDynamicDelegate__DelegateSignature // (Net|Exec|Event|NetResponse|UbergraphFunction|MulticastDelegate|NetServer|HasDefaults|NetClient|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f32810d20
	void LIMOnGetFriendRequestsDynamicDelegate__DelegateSignature(struct FLimNativeLowLevelWrapper& InWrapper, struct FLimNativeOnGetFriendRequestCallBack& RetData); // DelegateFunction LimNative.LimNative.LIMOnGetFriendRequestsDynamicDelegate__DelegateSignature // (Net|Exec|Event|NetResponse|UbergraphFunction|MulticastDelegate|NetServer|HasDefaults|NetClient|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f32810d20
	void LIMOnGetConvChatLevelConfigDynamicDelegate__DelegateSignature(struct FLimNativeLowLevelWrapper& InWrapper, struct FLimNativeOnGetConvChatLevelConfigCallBack& RetData); // DelegateFunction LimNative.LimNative.LIMOnGetConvChatLevelConfigDynamicDelegate__DelegateSignature // (Net|Exec|Event|NetResponse|UbergraphFunction|MulticastDelegate|NetServer|HasDefaults|NetClient|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f32810d20
	void LIMOnGetConnStateDynamicDelegate__DelegateSignature(struct FLimNativeLowLevelWrapper& InWrapper, struct FLimNativeGetConnStateCallBack& RetData); // DelegateFunction LimNative.LimNative.LIMOnGetConnStateDynamicDelegate__DelegateSignature // (Net|Exec|Event|NetResponse|UbergraphFunction|MulticastDelegate|NetServer|HasDefaults|NetClient|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f32810d20
	void LIMOnGetConfigDynamicDelegate__DelegateSignature(struct FLimNativeLowLevelWrapper& InWrapper, struct FLimNativeOnGetConfigCallBack& RetData); // DelegateFunction LimNative.LimNative.LIMOnGetConfigDynamicDelegate__DelegateSignature // (Net|Exec|Event|NetResponse|UbergraphFunction|MulticastDelegate|NetServer|HasDefaults|NetClient|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f32810d20
	void LIMOnGetCommonMsgsDynamicDelegate__DelegateSignature(struct FLimNativeLowLevelWrapper& InWrapper, struct FLimNativeOnGetCommonMsgsCallBack& RetData); // DelegateFunction LimNative.LimNative.LIMOnGetCommonMsgsDynamicDelegate__DelegateSignature // (Net|Exec|Event|NetResponse|UbergraphFunction|MulticastDelegate|NetServer|HasDefaults|NetClient|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f32810d20
	void LIMOnGetBlockeesDynamicDelegate__DelegateSignature(struct FLimNativeLowLevelWrapper& InWrapper, struct FLimNativeOnGetBlockeesCallBack& RetData); // DelegateFunction LimNative.LimNative.LIMOnGetBlockeesDynamicDelegate__DelegateSignature // (Net|Exec|Event|NetResponse|UbergraphFunction|MulticastDelegate|NetServer|HasDefaults|NetClient|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f32810d20
	void LIMOnGetAllGroupAttrDynamicDelegate__DelegateSignature(struct FLimNativeLowLevelWrapper& InWrapper, struct FLimNativeOnGroupAttrGetAllCallBack& RetData); // DelegateFunction LimNative.LimNative.LIMOnGetAllGroupAttrDynamicDelegate__DelegateSignature // (Net|Exec|Event|NetResponse|UbergraphFunction|MulticastDelegate|NetServer|HasDefaults|NetClient|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f32810d20
	void LIMOnDestoryGroupDynamicDelegate__DelegateSignature(struct FLimNativeLowLevelWrapper& InWrapper, struct FLimNativeOnGroupDestoryCallBack& RetData); // DelegateFunction LimNative.LimNative.LIMOnDestoryGroupDynamicDelegate__DelegateSignature // (Net|Exec|Event|NetResponse|UbergraphFunction|MulticastDelegate|NetServer|HasDefaults|NetClient|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f32810d20
	void LIMOnCreateGroupDynamicDelegate__DelegateSignature(struct FLimNativeLowLevelWrapper& InWrapper, struct FLimNativeOnCreateGroupCallBack& RetData); // DelegateFunction LimNative.LimNative.LIMOnCreateGroupDynamicDelegate__DelegateSignature // (Net|Exec|Event|NetResponse|UbergraphFunction|MulticastDelegate|NetServer|HasDefaults|NetClient|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f32810d20
	void LIMOnCreateFriendRequestDynamicDelegate__DelegateSignature(struct FLimNativeLowLevelWrapper& InWrapper, struct FLimNativeOnCreateFriendRequestCallBack& RetData); // DelegateFunction LimNative.LimNative.LIMOnCreateFriendRequestDynamicDelegate__DelegateSignature // (Net|Exec|Event|NetResponse|UbergraphFunction|MulticastDelegate|NetServer|HasDefaults|NetClient|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f32810d20
	void LIMOnConvsGetDynamicDelegate__DelegateSignature(struct FLimNativeLowLevelWrapper& InWrapper, struct FLimNativeOnConvsGetCallBack& RetData); // DelegateFunction LimNative.LimNative.LIMOnConvsGetDynamicDelegate__DelegateSignature // (Net|Exec|Event|NetResponse|UbergraphFunction|MulticastDelegate|NetServer|HasDefaults|NetClient|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f32810d20
	void LIMOnConvHandleynamicDelegate__DelegateSignature(struct FLimNativeLowLevelWrapper& InWrapper, struct FLimNativeOnConvHandleCallBack& RetData); // DelegateFunction LimNative.LimNative.LIMOnConvHandleynamicDelegate__DelegateSignature // (Net|Exec|Event|NetResponse|UbergraphFunction|MulticastDelegate|NetServer|HasDefaults|NetClient|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f32810d20
	void LIMOnCheckImageDynamicDelegate__DelegateSignature(struct FLimNativeLowLevelWrapper& InWrapper, struct FLimNativeDataCallBackBase& RetData); // DelegateFunction LimNative.LimNative.LIMOnCheckImageDynamicDelegate__DelegateSignature // (Net|Exec|Event|NetResponse|UbergraphFunction|MulticastDelegate|NetServer|HasDefaults|NetClient|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467fc0
	void LIMOnCancelFriendRequestDynamicDelegate__DelegateSignature(struct FLimNativeLowLevelWrapper& InWrapper, struct FLimNativeFriendCommonCallBack& RetData); // DelegateFunction LimNative.LimNative.LIMOnCancelFriendRequestDynamicDelegate__DelegateSignature // (Net|Exec|Event|NetResponse|UbergraphFunction|MulticastDelegate|NetServer|HasDefaults|NetClient|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467fc0
	void LIMOnAddToBlockeeDynamicDelegate__DelegateSignature(struct FLimNativeLowLevelWrapper& InWrapper, struct FLimNativeFriendCommonCallBack& RetData); // DelegateFunction LimNative.LimNative.LIMOnAddToBlockeeDynamicDelegate__DelegateSignature // (Net|Exec|Event|NetResponse|UbergraphFunction|MulticastDelegate|NetServer|HasDefaults|NetClient|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467fc0
	void LIMOnAddGroupMemberDynamicDelegate__DelegateSignature(struct FLimNativeLowLevelWrapper& InWrapper, struct FLimNativeOnGroupMemberAddCallBack& RetData); // DelegateFunction LimNative.LimNative.LIMOnAddGroupMemberDynamicDelegate__DelegateSignature // (Net|Exec|Event|NetResponse|UbergraphFunction|MulticastDelegate|NetServer|HasDefaults|NetClient|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f32810d20
	void LIMOnAcceptFriendRequestDynamicDelegate__DelegateSignature(struct FLimNativeLowLevelWrapper& InWrapper, struct FLimNativeFriendCommonCallBack& RetData); // DelegateFunction LimNative.LimNative.LIMOnAcceptFriendRequestDynamicDelegate__DelegateSignature // (Net|Exec|Event|NetResponse|UbergraphFunction|MulticastDelegate|NetServer|HasDefaults|NetClient|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f32810d20
	void LIMLogDynamicDelegate__DelegateSignature(struct FLimNativeLowLevelWrapper& InWrapper, struct FString InData); // DelegateFunction LimNative.LimNative.LIMLogDynamicDelegate__DelegateSignature // (Net|Exec|Event|NetResponse|UbergraphFunction|MulticastDelegate|NetServer|HasDefaults|NetClient|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467fc0
	void LIMEventDynamicDelegate__DelegateSignature(struct FLimNativeLowLevelWrapper& InWrapper, struct FString InData); // DelegateFunction LimNative.LimNative.LIMEventDynamicDelegate__DelegateSignature // (Net|Exec|Event|NetResponse|UbergraphFunction|MulticastDelegate|NetServer|HasDefaults|NetClient|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467fc0
	void JoinGroup(struct FLimNativeLowLevelWrapper& InCtx, struct FString groupid); // Function LimNative.LimNative.JoinGroup // (NetReliableNetRequest|Event|Static|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467fc0
	struct FLimNativeLowLevelWrapper InitLIM(struct FString InServerEnvID, struct FLimNativeInitConfig InConfig); // Function LimNative.LimNative.InitLIM // (Net|NetReliableExec|Native|Static|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f32810d20
	void GetUsersState(struct FLimNativeLowLevelWrapper& InCtx, struct TArray<struct FString>& InUserIDs); // Function LimNative.LimNative.GetUsersState // (NetReliableNetRequest|Native|Static|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467fc0
	void GetUsers(struct FLimNativeLowLevelWrapper& InCtx, struct FUidList& InUserIDs); // Function LimNative.LimNative.GetUsers // (Native|Static|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f32810d20
	void GetUser(struct FLimNativeLowLevelWrapper& InCtx, struct FString InUserId); // Function LimNative.LimNative.GetUser // (NetRequest|Exec|Static|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467fc0
	void GetResDir(struct FLimNativeLowLevelWrapper& InCtx); // Function LimNative.LimNative.GetResDir // (Net|Exec|Static|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467fc0
	void GetOssToken(struct FLimNativeLowLevelWrapper& InCtx); // Function LimNative.LimNative.GetOssToken // (Net|NetReliableNetRequest|Static|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467fc0
	void GetMiscConfigInfo(struct FLimNativeLowLevelWrapper& InCtx); // Function LimNative.LimNative.GetMiscConfigInfo // (NetRequest|Static|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467fc0
	void GetMessagesByID(struct FLimNativeLowLevelWrapper& InCtx, struct FString InConvID, enum class ELimNativeConvType InConvType, struct FString InFromMsgID, struct FString InToMsgID); // Function LimNative.LimNative.GetMessagesByID // (NetRequest|Exec|Native|Event|NetResponse|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467fc0
	struct FString GetLIMVersion(); // Function LimNative.LimNative.GetLIMVersion // (Net|NetReliableNetRequest|Native|Event|NetResponse|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467fc0
	struct ULimNative* GetLimNativeInstance(); // Function LimNative.LimNative.GetLimNativeInstance // (Net|NetReliableExec|Native|Event|NetResponse|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467fc0
	void GetLanguage(struct FLimNativeLowLevelWrapper& InCtx); // Function LimNative.LimNative.GetLanguage // (Net|Exec|Native|Event|NetResponse|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467fc0
	void GetGroups(struct FLimNativeLowLevelWrapper& InCtx, struct FString Tag, struct FString Size); // Function LimNative.LimNative.GetGroups // (Net|Native|Event|NetResponse|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467fc0
	void GetGroupMembers(struct FLimNativeLowLevelWrapper& InCtx, struct FString groupid, struct FString Tag, struct FString Size); // Function LimNative.LimNative.GetGroupMembers // (NetReliableExec|Event|NetResponse|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467fc0
	void GetGroupAttr(struct FLimNativeLowLevelWrapper& InCtx, struct FString groupid, struct FString Key); // Function LimNative.LimNative.GetGroupAttr // (NetRequest|Event|NetResponse|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467fc0
	void GetGroupAllAttr(struct FLimNativeLowLevelWrapper& InCtx, struct FString groupid); // Function LimNative.LimNative.GetGroupAllAttr // (Event|NetResponse|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467fc0
	void GetGroup(struct FLimNativeLowLevelWrapper& InCtx, struct FString groupid); // Function LimNative.LimNative.GetGroup // (NetRequest|Exec|Native|NetResponse|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467fc0
	void GetGMEToken(struct FLimNativeLowLevelWrapper& InCtx, struct FString InAppId, struct FString InUserId, struct FString InRoomId); // Function LimNative.LimNative.GetGMEToken // (Net|NetRequest|Native|NetResponse|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467fc0
	void GetFriendsV2(struct FLimNativeLowLevelWrapper& InCtx, bool InNeedPresence); // Function LimNative.LimNative.GetFriendsV2 // (Net|Native|NetResponse|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467fc0
	void GetFriends(struct FLimNativeLowLevelWrapper& InCtx, int32_t InTag, struct FString InSize, struct FString InExtra); // Function LimNative.LimNative.GetFriends // (Net|NetReliableExec|NetResponse|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467fc0
	void GetFriendRequests(struct FLimNativeLowLevelWrapper& InCtx, int32_t InTag, struct FString InSize, struct FString InExtra); // Function LimNative.LimNative.GetFriendRequests // (NetRequest|NetResponse|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467fc0
	void GetConvChatLevelConfig(struct FLimNativeLowLevelWrapper& InCtx); // Function LimNative.LimNative.GetConvChatLevelConfig // (Net|NetResponse|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467fc0
	void GetConnState(struct FLimNativeLowLevelWrapper& InCtx); // Function LimNative.LimNative.GetConnState // (Net|NetReliableNetRequest|Exec|Native|Event|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467fc0
	void GetBlockees(struct FLimNativeLowLevelWrapper& InCtx, int32_t InTag, struct FString InSize, struct FString InExtra); // Function LimNative.LimNative.GetBlockees // (Exec|Native|Event|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467fc0
	void GetBeforeMessages(struct FLimNativeLowLevelWrapper& InCtx, struct FString ConvID, enum class ELimNativeConvType ConvType, int32_t MsgId); // Function LimNative.LimNative.GetBeforeMessages // (NetReliableNative|Event|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467fc0
	void GetAfterMessages(struct FLimNativeLowLevelWrapper& InCtx, struct FString ConvID, enum class ELimNativeConvType ConvType, int32_t MsgId); // Function LimNative.LimNative.GetAfterMessages // (NetRequest|Exec|Event|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467fc0
	void DestoryLimNativeInstance(); // Function LimNative.LimNative.DestoryLimNativeInstance // (Net|NetReliableExec|Event|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467fc0
	void DestoryGroup(struct FLimNativeLowLevelWrapper& InCtx, struct FString groupid); // Function LimNative.LimNative.DestoryGroup // (Net|NetReliableNetRequest|Event|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467fc0
	struct FLimNativeLowLevelWrapper CreateLIM(struct FString InServerEnvID); // Function LimNative.LimNative.CreateLIM // (NetRequest|Event|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467fc0
	void CreateGroup(struct FLimNativeLowLevelWrapper& InCtx, struct FString Name, struct TArray<struct FString>& members, struct FString Extra); // Function LimNative.LimNative.CreateGroup // (NetRequest|Exec|Native|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467fc0
	void CreateFriendRequest(struct FLimNativeLowLevelWrapper& InCtx, struct FString InUserId, struct FString InExtra); // Function LimNative.LimNative.CreateFriendRequest // (NetReliableNetRequest|Native|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467fc0
	void ConversationsGet(struct FLimNativeLowLevelWrapper& InCtx, int32_t Size, struct FString Extra); // Function LimNative.LimNative.ConversationsGet // (Net|Native|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467fc0
	void ConversationSetSticky(); // Function LimNative.LimNative.ConversationSetSticky // (Native|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467fc0
	void ConversationSetRead(); // Function LimNative.LimNative.ConversationSetRead // (Native|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467fc0
	void ConversationSetMute(); // Function LimNative.LimNative.ConversationSetMute // (Native|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467fc0
	void ConversationSetHide(); // Function LimNative.LimNative.ConversationSetHide // (Native|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467fc0
	void ConversationDiscard(struct FLimNativeLowLevelWrapper& InCtx, struct FString ConvID, enum class ELimNativeConvType ConvType); // Function LimNative.LimNative.ConversationDiscard // (Net|NetReliableExec|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467fc0
	void CheckImage(struct FLimNativeLowLevelWrapper& InCtx, struct FString InUrl); // Function LimNative.LimNative.CheckImage // (Net|NetReliableNetRequest|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467fc0
	void CancelFriendRequest(struct FLimNativeLowLevelWrapper& InCtx, struct FString InUserId, struct FString InRequestID, struct FString InExtra); // Function LimNative.LimNative.CancelFriendRequest // (Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467fc0
	void AddToBlockee(struct FLimNativeLowLevelWrapper& InCtx, struct FString InUserId); // Function LimNative.LimNative.AddToBlockee // (NetRequest|Exec|Native|Event|NetResponse|Static|NetMulticast|UbergraphFunction|MulticastDelegate|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467fc0
	void AddGroupMember(struct FLimNativeLowLevelWrapper& InCtx, struct FString groupid, struct FString memberid); // Function LimNative.LimNative.AddGroupMember // (NetReliableNetRequest|Native|Event|NetResponse|Static|NetMulticast|UbergraphFunction|MulticastDelegate|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467fc0
	void AcceptFriendRequest(struct FLimNativeLowLevelWrapper& InCtx, struct FString InRequestID, struct FString InExtra); // Function LimNative.LimNative.AcceptFriendRequest // (Native|Event|NetResponse|Static|NetMulticast|UbergraphFunction|MulticastDelegate|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467fc0
};

// Class LimNative.LimNativeChatMsgReader
// Size: 0x28 (Inherited: 0x28)
struct ULimNativeChatMsgReader : UObject {

	struct FLimNativeIMVoiceMessage GetVoiceMessage(struct FLimNativeIMChatMessage& MsgStructWrapper, struct FLimNativeIMChatMessageInfo& MsgInfo); // Function LimNative.LimNativeChatMsgReader.GetVoiceMessage // (NetRequest|Exec|Event|NetMulticast|MulticastDelegate|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467b40
	struct FLimNativeIMTextMessage GetTextMessage(struct FLimNativeIMChatMessage& MsgStructWrapper, struct FLimNativeIMChatMessageInfo& MsgInfo); // Function LimNative.LimNativeChatMsgReader.GetTextMessage // (Net|Event|NetMulticast|MulticastDelegate|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467d80
	struct FLimNativeIMShareMessage GetShareMessage(struct FLimNativeIMChatMessage& MsgStructWrapper, struct FLimNativeIMChatMessageInfo& MsgInfo); // Function LimNative.LimNativeChatMsgReader.GetShareMessage // (Exec|Native|NetMulticast|MulticastDelegate|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467d80
	struct FLimNativeIMNotificationMessage GetNotificationMessage(struct FLimNativeIMChatMessage& MsgStructWrapper, struct FLimNativeIMChatMessageInfo& MsgInfo); // Function LimNative.LimNativeChatMsgReader.GetNotificationMessage // (Net|NetRequest|Exec|NetMulticast|MulticastDelegate|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467d80
	struct FLimNativeIMImageMessage GetImageMessage(struct FLimNativeIMChatMessage& MsgStructWrapper, struct FLimNativeIMChatMessageInfo& MsgInfo); // Function LimNative.LimNativeChatMsgReader.GetImageMessage // (Net|NetReliableNetRequest|Exec|Native|Event|NetResponse|Static|MulticastDelegate|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467d80
	struct FLimNativeIMEmotionMessage GetEmotionMessage(struct FLimNativeIMChatMessage& MsgStructWrapper, struct FLimNativeIMChatMessageInfo& MsgInfo); // Function LimNative.LimNativeChatMsgReader.GetEmotionMessage // (NetReliableNative|Event|NetResponse|Static|MulticastDelegate|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467d80
};

// Class LimNative.LimNativeHelper
// Size: 0x28 (Inherited: 0x28)
struct ULimNativeHelper : UObject {

	int32_t NameStringToEnumValue(struct FString Enum, struct FString EnumName); // Function LimNative.LimNativeHelper.NameStringToEnumValue // (Net|NetReliableNetRequest|Event|Static|UbergraphFunction|MulticastDelegate|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f314676c0
	struct FString GetUE4LogFilePath(); // Function LimNative.LimNativeHelper.GetUE4LogFilePath // (Net|Static|UbergraphFunction|MulticastDelegate|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467b40
	struct FString GetSavedPath(); // Function LimNative.LimNativeHelper.GetSavedPath // (Net|NetReliableNetRequest|Native|Event|NetResponse|UbergraphFunction|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467b40
	struct FString GetProjectPath(); // Function LimNative.LimNativeHelper.GetProjectPath // (Net|NetReliableNetRequest|Exec|Native|Event|NetResponse|UbergraphFunction|MulticastDelegate|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467b40
	struct FString GetProjectContentPath(); // Function LimNative.LimNativeHelper.GetProjectContentPath // (Net|NetRequest|Exec|Native|Event|NetResponse|UbergraphFunction|MulticastDelegate|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467b40
	struct FString GetGamePersistentDownloadDir(); // Function LimNative.LimNativeHelper.GetGamePersistentDownloadDir // (Net|NetReliableNetResponse|UbergraphFunction|MulticastDelegate|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467b40
	struct FString GetFileText(struct FString Path); // Function LimNative.LimNativeHelper.GetFileText // (NetRequest|Exec|Event|UbergraphFunction|MulticastDelegate|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467b40
	struct TArray<char> GetFileBinary(struct FString Path); // Function LimNative.LimNativeHelper.GetFileBinary // (Net|Exec|Event|UbergraphFunction|MulticastDelegate|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467b40
	struct TArray<struct FString> EnumToStringArray(struct FString Enum, bool bExcludeHidden); // Function LimNative.LimNativeHelper.EnumToStringArray // (Net|NetReliableNetRequest|Exec|Native|Event|NetResponse|Static|NetMulticast|MulticastDelegate|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467b40
	struct FString EnumToString(struct FString Enum, int32_t EnumValue); // Function LimNative.LimNativeHelper.EnumToString // (Net|NetReliableExec|Native|Event|NetResponse|Static|NetMulticast|MulticastDelegate|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467b40
	struct TArray<struct FString> EnumToNameStringArray(struct FString Enum, bool bExcludeHidden); // Function LimNative.LimNativeHelper.EnumToNameStringArray // (NetReliableNetRequest|Native|Event|NetResponse|Static|NetMulticast|MulticastDelegate|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467b40
	struct FString EnumToNameString(struct FString Enum, int32_t EnumValue); // Function LimNative.LimNativeHelper.EnumToNameString // (NetReliableNative|Event|NetResponse|Static|NetMulticast|MulticastDelegate|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467b40
};

// Class LimNative.LimNativeLowLevel
// Size: 0x418 (Inherited: 0x28)
struct ULimNativeLowLevel : UObject {
	struct FMulticastInlineDelegate OnEvent; // 0x28(0x10)
	struct FMulticastInlineDelegate OnLog; // 0x38(0x10)
	struct FMulticastInlineDelegate OnCall; // 0x48(0x10)
	struct FMulticastInlineDelegate OnSetConfig; // 0x58(0x10)
	struct FMulticastInlineDelegate OnSetAllConfigs; // 0x68(0x10)
	struct FMulticastInlineDelegate OnGetConfig; // 0x78(0x10)
	struct FMulticastInlineDelegate OnGetAllConfigs; // 0x88(0x10)
	struct FMulticastInlineDelegate OnLogin; // 0x98(0x10)
	struct FMulticastInlineDelegate OnLoginV2; // 0xa8(0x10)
	struct FMulticastInlineDelegate OnLogout; // 0xb8(0x10)
	struct FMulticastInlineDelegate OnSendMsg; // 0xc8(0x10)
	struct FMulticastInlineDelegate OnRevokeMsg; // 0xd8(0x10)
	struct FMulticastInlineDelegate OnGetMsgs; // 0xe8(0x10)
	struct FMulticastInlineDelegate OnGetMsgsV2; // 0xf8(0x10)
	struct FMulticastInlineDelegate OnSetMsgRead; // 0x108(0x10)
	struct FMulticastInlineDelegate OnSetMsgState; // 0x118(0x10)
	struct FMulticastInlineDelegate OnCreateConv; // 0x128(0x10)
	struct FMulticastInlineDelegate OnDestroyConv; // 0x138(0x10)
	struct FMulticastInlineDelegate OnClearConv; // 0x148(0x10)
	struct FMulticastInlineDelegate OnGetConvs; // 0x158(0x10)
	struct FMulticastInlineDelegate OnGetConv; // 0x168(0x10)
	struct FMulticastInlineDelegate OnSetConvRead; // 0x178(0x10)
	struct FMulticastInlineDelegate OnSetConvSticky; // 0x188(0x10)
	struct FMulticastInlineDelegate OnSetConvMute; // 0x198(0x10)
	struct FMulticastInlineDelegate OnGetConvAttr; // 0x1a8(0x10)
	struct FMulticastInlineDelegate OnGetConvAllAttrs; // 0x1b8(0x10)
	struct FMulticastInlineDelegate OnSetConvAttr; // 0x1c8(0x10)
	struct FMulticastInlineDelegate OnCreateGroup; // 0x1d8(0x10)
	struct FMulticastInlineDelegate OnJoinGroup; // 0x1e8(0x10)
	struct FMulticastInlineDelegate OnQuitGroup; // 0x1f8(0x10)
	struct FMulticastInlineDelegate OnDestroyGroup; // 0x208(0x10)
	struct FMulticastInlineDelegate OnGetGroup; // 0x218(0x10)
	struct FMulticastInlineDelegate OnSetGroup; // 0x228(0x10)
	struct FMulticastInlineDelegate OnGetGroups; // 0x238(0x10)
	struct FMulticastInlineDelegate OnGetGroupAttr; // 0x248(0x10)
	struct FMulticastInlineDelegate OnGetGroupAllAttrs; // 0x258(0x10)
	struct FMulticastInlineDelegate OnSetGroupAttr; // 0x268(0x10)
	struct FMulticastInlineDelegate OnGetGroupMembers; // 0x278(0x10)
	struct FMulticastInlineDelegate OnGetGroupMember; // 0x288(0x10)
	struct FMulticastInlineDelegate OnAddGroupMember; // 0x298(0x10)
	struct FMulticastInlineDelegate OnRemoveGroupMember; // 0x2a8(0x10)
	struct FMulticastInlineDelegate OnGetFriends; // 0x2b8(0x10)
	struct FMulticastInlineDelegate OnRemoveFriend; // 0x2c8(0x10)
	struct FMulticastInlineDelegate OnGetFriendRequests; // 0x2d8(0x10)
	struct FMulticastInlineDelegate OnCreateFriendRequest; // 0x2e8(0x10)
	struct FMulticastInlineDelegate OnAcceptFriendRequest; // 0x2f8(0x10)
	struct FMulticastInlineDelegate OnRefuseFriendRequest; // 0x308(0x10)
	struct FMulticastInlineDelegate OnCancelFriendRequest; // 0x318(0x10)
	struct FMulticastInlineDelegate OnGetBlockees; // 0x328(0x10)
	struct FMulticastInlineDelegate OnAddToBlockee; // 0x338(0x10)
	struct FMulticastInlineDelegate OnRemoveFromBlockee; // 0x348(0x10)
	struct FMulticastInlineDelegate OnBlockeeExists; // 0x358(0x10)
	struct FMulticastInlineDelegate OnGetUser; // 0x368(0x10)
	struct FMulticastInlineDelegate OnGetUsers; // 0x378(0x10)
	struct FMulticastInlineDelegate OnGetUsersState; // 0x388(0x10)
	struct FMulticastInlineDelegate OnGetOssToken; // 0x398(0x10)
	struct FMulticastInlineDelegate OnGetGMEToken; // 0x3a8(0x10)
	struct FMulticastInlineDelegate OnReportMsg; // 0x3b8(0x10)
	struct FMulticastInlineDelegate OnTranslateText; // 0x3c8(0x10)
	struct FMulticastInlineDelegate OnCheckImage; // 0x3d8(0x10)
	struct FMulticastInlineDelegate OnGetMiscConfigInfo; // 0x3e8(0x10)
	struct FMulticastInlineDelegate OnGetConvChatLevelConfig; // 0x3f8(0x10)
	struct FMulticastInlineDelegate OnGetConnState; // 0x408(0x10)

	void TranslateText(struct FLimNativeLowLevelWrapper& InCtx, struct FString InText, enum class ELimNativeSupportedLanguage InLang); // Function LimNative.LimNativeLowLevel.TranslateText // (Net|Native|NetMulticast|UbergraphFunction|MulticastDelegate|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f32810d20
	void SetMsgState(struct FLimNativeLowLevelWrapper& InCtx, struct FString InMsgParams); // Function LimNative.LimNativeLowLevel.SetMsgState // (Net|NetRequest|Exec|NetMulticast|UbergraphFunction|MulticastDelegate|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467900
	void SetMsgRead(struct FLimNativeLowLevelWrapper& InCtx, struct FString InConvID, enum class ELimNativeConvType InConvType, struct FString InMsgID, struct FString InExtra); // Function LimNative.LimNativeLowLevel.SetMsgRead // (Net|NetRequest|NetMulticast|UbergraphFunction|MulticastDelegate|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467900
	void SetLogHandler(struct FLimNativeLowLevelWrapper& InCtx); // Function LimNative.LimNativeLowLevel.SetLogHandler // (NetReliableNetMulticast|UbergraphFunction|MulticastDelegate|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467900
	void SetGroupAttr(struct FLimNativeLowLevelWrapper& InCtx, struct FString InGroupID, struct FString InKey, struct FString InValue); // Function LimNative.LimNativeLowLevel.SetGroupAttr // (NetRequest|Exec|Native|Event|NetResponse|Static|UbergraphFunction|MulticastDelegate|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467900
	void SetGroup(struct FLimNativeLowLevelWrapper& InCtx, struct FString InGroupID, struct FString InGroupName, struct FString InExtra); // Function LimNative.LimNativeLowLevel.SetGroup // (Net|NetRequest|Native|Event|NetResponse|Static|UbergraphFunction|MulticastDelegate|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467900
	void SetEventHandler(struct FLimNativeLowLevelWrapper& InCtx); // Function LimNative.LimNativeLowLevel.SetEventHandler // (NetReliableNative|Event|NetResponse|Static|UbergraphFunction|MulticastDelegate|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467900
	void SetConvSticky(struct FLimNativeLowLevelWrapper& InCtx, struct FString InConvID, enum class ELimNativeConvType InConvType, bool bSticky); // Function LimNative.LimNativeLowLevel.SetConvSticky // (NetRequest|Exec|Event|NetResponse|Static|UbergraphFunction|MulticastDelegate|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467900
	void SetConvRead(struct FLimNativeLowLevelWrapper& InCtx, struct FString InConvID, enum class ELimNativeConvType InConvType, struct FString InMsgID, struct FString InExtra); // Function LimNative.LimNativeLowLevel.SetConvRead // (NetRequest|Event|NetResponse|Static|UbergraphFunction|MulticastDelegate|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467900
	void SetConvMute(struct FLimNativeLowLevelWrapper& InCtx, struct FString InConvID, enum class ELimNativeConvType InConvType, bool bMute); // Function LimNative.LimNativeLowLevel.SetConvMute // (Net|NetRequest|Exec|Native|NetResponse|Static|UbergraphFunction|MulticastDelegate|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467900
	void SetConvAttr(struct FLimNativeLowLevelWrapper& InCtx, struct FString InConvID, enum class ELimNativeConvType InConvType, struct FString InKey, struct FString InValue); // Function LimNative.LimNativeLowLevel.SetConvAttr // (NetReliableNetRequest|Native|NetResponse|Static|UbergraphFunction|MulticastDelegate|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467900
	void SetAllConfigs(struct FLimNativeLowLevelWrapper& InCtx, struct FString InJsonString); // Function LimNative.LimNativeLowLevel.SetAllConfigs // (Net|Native|NetResponse|Static|UbergraphFunction|MulticastDelegate|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467900
	void SendMsg(struct FLimNativeLowLevelWrapper& InCtx, struct FString InMsg); // Function LimNative.LimNativeLowLevel.SendMsg // (Net|NetRequest|Exec|NetResponse|Static|UbergraphFunction|MulticastDelegate|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467900
	void RevokeMsg(struct FLimNativeLowLevelWrapper& InCtx, struct FString InMsg); // Function LimNative.LimNativeLowLevel.RevokeMsg // (Net|Exec|NetResponse|Static|UbergraphFunction|MulticastDelegate|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467900
	void Resume(struct FLimNativeLowLevelWrapper& InCtx); // Function LimNative.LimNativeLowLevel.Resume // (Net|Exec|Native|Event|NetResponse|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467900
	void ReportMsg(struct FLimNativeLowLevelWrapper& InCtx, struct FString InMsg); // Function LimNative.LimNativeLowLevel.ReportMsg // (Net|NetRequest|NetResponse|Static|UbergraphFunction|MulticastDelegate|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467900
	void RemoveGroupMember(struct FLimNativeLowLevelWrapper& InCtx, struct FString InGroupID, struct FString InMemberID); // Function LimNative.LimNativeLowLevel.RemoveGroupMember // (Net|NetReliableNetRequest|Exec|Native|Event|Static|UbergraphFunction|MulticastDelegate|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467900
	void RemoveFromBlockee(struct FLimNativeLowLevelWrapper& InCtx, struct FString InUserId); // Function LimNative.LimNativeLowLevel.RemoveFromBlockee // (Net|NetReliableExec|Native|Event|Static|UbergraphFunction|MulticastDelegate|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467900
	void RemoveFriend(struct FLimNativeLowLevelWrapper& InCtx, struct FString InUserId, struct FString InExtra); // Function LimNative.LimNativeLowLevel.RemoveFriend // (Net|NetRequest|Native|Event|Static|UbergraphFunction|MulticastDelegate|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467900
	void RefuseFriendRequest(struct FLimNativeLowLevelWrapper& InCtx, struct FString InRequestID, struct FString InExtra); // Function LimNative.LimNativeLowLevel.RefuseFriendRequest // (Net|NetReliableNetRequest|Exec|Event|Static|UbergraphFunction|MulticastDelegate|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467900
	void QuitGroup(struct FLimNativeLowLevelWrapper& InCtx, struct FString InGroupID); // Function LimNative.LimNativeLowLevel.QuitGroup // (Net|NetReliableExec|Event|Static|UbergraphFunction|MulticastDelegate|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467900
	void Pause(struct FLimNativeLowLevelWrapper& InCtx); // Function LimNative.LimNativeLowLevel.Pause // (Net|Exec|Native|Event|NetResponse|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467900
	void Logout(struct FLimNativeLowLevelWrapper& InCtx); // Function LimNative.LimNativeLowLevel.Logout // (NetRequest|Event|Static|UbergraphFunction|MulticastDelegate|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467900
	void LoginV2(struct FLimNativeLowLevelWrapper& InCtx, struct FString InEnv, struct FString InRoleID); // Function LimNative.LimNativeLowLevel.LoginV2 // (Net|NetReliableNetRequest|Exec|Native|Static|UbergraphFunction|MulticastDelegate|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467900
	void Login(struct FLimNativeLowLevelWrapper& InCtx, struct FString InAppId, struct FString InAppUserID, struct FString InToken, struct FString InRoleID, struct FString InExtra); // Function LimNative.LimNativeLowLevel.Login // (Net|NetRequest|Native|Static|UbergraphFunction|MulticastDelegate|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467900
	void LIMResultDynamicDelegate__DelegateSignature(struct FLimNativeLowLevelWrapper& InWrapper, struct FString InData); // DelegateFunction LimNative.LimNativeLowLevel.LIMResultDynamicDelegate__DelegateSignature // (Net|Exec|Event|NetResponse|UbergraphFunction|MulticastDelegate|NetServer|HasDefaults|NetClient|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467900
	void LIMLogDynamicDelegate__DelegateSignature(struct FLimNativeLowLevelWrapper& InWrapper, struct FString InData); // DelegateFunction LimNative.LimNativeLowLevel.LIMLogDynamicDelegate__DelegateSignature // (Net|Exec|Event|NetResponse|UbergraphFunction|MulticastDelegate|NetServer|HasDefaults|NetClient|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467900
	void LIMEventDynamicDelegate__DelegateSignature(struct FLimNativeLowLevelWrapper& InWrapper, struct FString InData); // DelegateFunction LimNative.LimNativeLowLevel.LIMEventDynamicDelegate__DelegateSignature // (Net|Exec|Event|NetResponse|UbergraphFunction|MulticastDelegate|NetServer|HasDefaults|NetClient|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467900
	void JoinGroup(struct FLimNativeLowLevelWrapper& InCtx, struct FString InGroupID); // Function LimNative.LimNativeLowLevel.JoinGroup // (Net|Native|Static|UbergraphFunction|MulticastDelegate|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467900
	void GetUsersState(struct FLimNativeLowLevelWrapper& InCtx, struct TArray<struct FString>& InUserIDs); // Function LimNative.LimNativeLowLevel.GetUsersState // (NetRequest|Exec|Static|UbergraphFunction|MulticastDelegate|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467900
	void GetUsers(struct FLimNativeLowLevelWrapper& InCtx, struct FString InUserIDs); // Function LimNative.LimNativeLowLevel.GetUsers // (Net|NetReliableNetRequest|Static|UbergraphFunction|MulticastDelegate|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467900
	void GetUser(struct FLimNativeLowLevelWrapper& InCtx, struct FString InUserId); // Function LimNative.LimNativeLowLevel.GetUser // (Net|NetReliableStatic|UbergraphFunction|MulticastDelegate|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467900
	void GetOssToken(struct FLimNativeLowLevelWrapper& InCtx); // Function LimNative.LimNativeLowLevel.GetOssToken // (NetReliableExec|Native|Event|NetResponse|UbergraphFunction|MulticastDelegate|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467900
	void GetMsgsV2(struct FLimNativeLowLevelWrapper& InCtx, struct FString InConvID, enum class ELimNativeConvType InConvType, struct FString InFromMsgID, struct FString InToMsgID); // Function LimNative.LimNativeLowLevel.GetMsgsV2 // (Net|NetReliableNative|Event|NetResponse|UbergraphFunction|MulticastDelegate|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467900
	void GetMsgs(struct FLimNativeLowLevelWrapper& InCtx, struct FString InConvID, enum class ELimNativeConvType InConvType, enum class ELimNativeMsgDirType InDir, struct FString InMsgID, struct FString InExtra); // Function LimNative.LimNativeLowLevel.GetMsgs // (NetReliableExec|Event|NetResponse|UbergraphFunction|MulticastDelegate|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f32810d20
	void GetMiscConfigInfo(struct FLimNativeLowLevelWrapper& InCtx); // Function LimNative.LimNativeLowLevel.GetMiscConfigInfo // (Net|NetReliableNetRequest|Event|NetResponse|UbergraphFunction|MulticastDelegate|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467900
	struct FString GetLIMVersion(); // Function LimNative.LimNativeLowLevel.GetLIMVersion // (Net|NetReliableNetRequest|Native|Event|NetResponse|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467900
	struct ULimNativeLowLevel* GetInstance(); // Function LimNative.LimNativeLowLevel.GetInstance // (Net|NetReliableNetRequest|Event|NetResponse|UbergraphFunction|MulticastDelegate|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467900
	void GetGroups(struct FLimNativeLowLevelWrapper& InCtx, int32_t InTag, int32_t InSize, struct FString InExtra); // Function LimNative.LimNativeLowLevel.GetGroups // (Event|NetResponse|UbergraphFunction|MulticastDelegate|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467900
	void GetGroupMembers(struct FLimNativeLowLevelWrapper& InCtx, struct FString InGroupID, int32_t InTag, int32_t InSize, struct FString InExtra); // Function LimNative.LimNativeLowLevel.GetGroupMembers // (Net|Exec|Native|NetResponse|UbergraphFunction|MulticastDelegate|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467900
	void GetGroupMember(struct FLimNativeLowLevelWrapper& InCtx, struct FString InGroupID, struct FString InMemberID); // Function LimNative.LimNativeLowLevel.GetGroupMember // (Net|NetReliableNative|NetResponse|UbergraphFunction|MulticastDelegate|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467900
	void GetGroupAttr(struct FLimNativeLowLevelWrapper& InCtx, struct FString InGroupID, struct FString InKey); // Function LimNative.LimNativeLowLevel.GetGroupAttr // (NetReliableNetRequest|Exec|NetResponse|UbergraphFunction|MulticastDelegate|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467900
	void GetGroupAllAttrs(struct FLimNativeLowLevelWrapper& InCtx, struct FString InGroupID); // Function LimNative.LimNativeLowLevel.GetGroupAllAttrs // (Net|Exec|NetResponse|UbergraphFunction|MulticastDelegate|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467900
	void GetGroup(struct FLimNativeLowLevelWrapper& InCtx, struct FString InGroupID); // Function LimNative.LimNativeLowLevel.GetGroup // (Net|NetRequest|NetResponse|UbergraphFunction|MulticastDelegate|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467900
	void GetGMEToken(struct FLimNativeLowLevelWrapper& InCtx, struct FString InAppId, struct FString InUserId, struct FString InRoomId); // Function LimNative.LimNativeLowLevel.GetGMEToken // (NetRequest|Exec|Native|Event|UbergraphFunction|MulticastDelegate|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467900
	void GetFriends(struct FLimNativeLowLevelWrapper& InCtx, int32_t InTag, int32_t InSize, struct FString InExtra); // Function LimNative.LimNativeLowLevel.GetFriends // (NetReliableNetRequest|Native|Event|UbergraphFunction|MulticastDelegate|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467900
	void GetFriendRequests(struct FLimNativeLowLevelWrapper& InCtx, int32_t InTag, int32_t InSize, struct FString InExtra); // Function LimNative.LimNativeLowLevel.GetFriendRequests // (Native|Event|UbergraphFunction|MulticastDelegate|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467900
	void GetConvs(struct FLimNativeLowLevelWrapper& InCtx, int32_t InSize, struct FString InExtra); // Function LimNative.LimNativeLowLevel.GetConvs // (NetRequest|Event|UbergraphFunction|MulticastDelegate|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467900
	void GetConvChatLevelConfig(struct FLimNativeLowLevelWrapper& InCtx); // Function LimNative.LimNativeLowLevel.GetConvChatLevelConfig // (Net|Event|UbergraphFunction|MulticastDelegate|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467900
	void GetConvAttr(struct FLimNativeLowLevelWrapper& InCtx, struct FString InConvID, enum class ELimNativeConvType InConvType, struct FString InKey); // Function LimNative.LimNativeLowLevel.GetConvAttr // (NetReliableExec|Native|UbergraphFunction|MulticastDelegate|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467900
	void GetConvAllAttrs(struct FLimNativeLowLevelWrapper& InCtx, struct FString InConvID, enum class ELimNativeConvType InConvType); // Function LimNative.LimNativeLowLevel.GetConvAllAttrs // (Net|NetRequest|Native|UbergraphFunction|MulticastDelegate|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467900
	void GetConv(struct FLimNativeLowLevelWrapper& InCtx, struct FString InConvID, enum class ELimNativeConvType InConvType); // Function LimNative.LimNativeLowLevel.GetConv // (Native|UbergraphFunction|MulticastDelegate|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467900
	void GetConnState(struct FLimNativeLowLevelWrapper& InCtx); // Function LimNative.LimNativeLowLevel.GetConnState // (Net|NetRequest|Exec|UbergraphFunction|MulticastDelegate|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467900
	void GetBlockees(struct FLimNativeLowLevelWrapper& InCtx, int32_t InTag, int32_t InSize, struct FString InExtra); // Function LimNative.LimNativeLowLevel.GetBlockees // (Net|NetReliableNetRequest|UbergraphFunction|MulticastDelegate|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467900
	void GetAllConfigs(struct FLimNativeLowLevelWrapper& InCtx); // Function LimNative.LimNativeLowLevel.GetAllConfigs // (NetRequest|UbergraphFunction|MulticastDelegate|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467900
	void DestroyGroup(struct FLimNativeLowLevelWrapper& InCtx, struct FString InGroupID); // Function LimNative.LimNativeLowLevel.DestroyGroup // (NetReliableNetRequest|Exec|Event|NetResponse|Static|NetMulticast|MulticastDelegate|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467900
	void DestroyConv(struct FLimNativeLowLevelWrapper& InCtx, struct FString InConvID, enum class ELimNativeConvType InConvType); // Function LimNative.LimNativeLowLevel.DestroyConv // (Exec|Event|NetResponse|Static|NetMulticast|MulticastDelegate|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467900
	void DestoryInstance(); // Function LimNative.LimNativeLowLevel.DestoryInstance // (Exec|Event|NetResponse|Static|NetMulticast|MulticastDelegate|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467900
	struct FLimNativeLowLevelWrapper CreateLIM(struct FString InServerEnvID); // Function LimNative.LimNativeLowLevel.CreateLIM // (NetRequest|Event|NetResponse|Static|NetMulticast|MulticastDelegate|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467900
	void CreateGroup(struct FLimNativeLowLevelWrapper& InCtx, struct TArray<struct FString> InMembers, struct FString InGroupName, struct FString InExtra); // Function LimNative.LimNativeLowLevel.CreateGroup // (Net|Exec|Native|NetResponse|Static|NetMulticast|MulticastDelegate|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467900
	void CreateFriendRequest(struct FLimNativeLowLevelWrapper& InCtx, struct FString InUserId, struct FString InExtra); // Function LimNative.LimNativeLowLevel.CreateFriendRequest // (NetRequest|Native|NetResponse|Static|NetMulticast|MulticastDelegate|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467900
	void CreateConv(struct FLimNativeLowLevelWrapper& InCtx, struct FString InConvID, enum class ELimNativeConvType InConvType, struct FString InExtra); // Function LimNative.LimNativeLowLevel.CreateConv // (Net|NetRequest|Exec|NetResponse|Static|NetMulticast|MulticastDelegate|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467900
	void ClearConv(struct FLimNativeLowLevelWrapper& InCtx, struct FString InConvID, enum class ELimNativeConvType InConvType); // Function LimNative.LimNativeLowLevel.ClearConv // (Exec|NetResponse|Static|NetMulticast|MulticastDelegate|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f32810d20
	void CheckImage(struct FLimNativeLowLevelWrapper& InCtx, struct FString InUrl); // Function LimNative.LimNativeLowLevel.CheckImage // (Net|NetReliableNetResponse|Static|NetMulticast|MulticastDelegate|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467900
	void CancelFriendRequest(struct FLimNativeLowLevelWrapper& InCtx, struct FString InUserId, struct FString InRequestID, struct FString InExtra); // Function LimNative.LimNativeLowLevel.CancelFriendRequest // (Net|NetRequest|Exec|Native|Event|Static|NetMulticast|MulticastDelegate|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467900
	void Call(struct FLimNativeLowLevelWrapper& InCtx, struct FString InJsonString); // Function LimNative.LimNativeLowLevel.Call // (Exec|Native|Event|Static|NetMulticast|MulticastDelegate|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467900
	void BlockeeExists(struct FLimNativeLowLevelWrapper& InCtx, struct FString InUserId); // Function LimNative.LimNativeLowLevel.BlockeeExists // (NetRequest|Native|Event|Static|NetMulticast|MulticastDelegate|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467900
	void AddToBlockee(struct FLimNativeLowLevelWrapper& InCtx, struct FString InUserId); // Function LimNative.LimNativeLowLevel.AddToBlockee // (Native|Event|Static|NetMulticast|MulticastDelegate|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467900
	void AddGroupMember(struct FLimNativeLowLevelWrapper& InCtx, struct FString InGroupID, struct FString InMemberID); // Function LimNative.LimNativeLowLevel.AddGroupMember // (NetReliableExec|Event|Static|NetMulticast|MulticastDelegate|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f31467900
	void AcceptFriendRequest(struct FLimNativeLowLevelWrapper& InCtx, struct FString InRequestID, struct FString InExtra); // Function LimNative.LimNativeLowLevel.AcceptFriendRequest // (NetRequest|Event|Static|NetMulticast|MulticastDelegate|Public|Private|Delegate|BlueprintCallable|BlueprintEvent|NetValidate) // @ game+0xffff822f32810d20
};

